### ISSUE TITLE
Particle system

### ISSUE THREAD

**Issue by BearishSun** [GameFoundry/bsf#10]
Full blown particle system with the following features:
 - Billboard particles with a variety of blend modes, as well as 3D mesh "particles"
 - Texture sheet and generic sprite animation (related to the 2D system changes)
 - Variety of emitter types, including all basic shapes, as well as meshes (including animated meshes)
 - A set of evolvers that control particle life-time and properties
 - Ability to set constant values, random range or value curves for majority of properties
 - Both CPU and GPU particle systems. GPU system will likely allow for a limited sub-set of evolvers but a much higher particle count.
 - Particle collisions, including collisions with basic shapes and screen space collisions
 - Soft particle rendering
 - Ability to emit in bursts
 - Ability to nest and spawn emitters by other emitters (complex effects)
 - Research for anything more?

**Comment by BearishSun** [comment]
Thanks, I'll keep those in mind.

Regarding restricting particles within a specific geometry, is that different from using collisions to restrict particle movement?

**Comment by nemerle** [comment]
I think it is, you render the particle system over the geometry and use stencil to prevent it from interacting with surrounding pixels, a few examples that come to mind:

* beam-me-up Scotty -> drawing a particle effect inside the player's mesh
* A fizzy water/fluid insight a container - particle system to simulate bubbles in a glass of water/ droplets on a window pane, etc.
* A particle-system based effect on an element of a snazzy futuristic armor

**Comment by BearishSun** [comment]
Makes sense. If you can think of a tool/engine that already has this functionality let me know, always easier to implement something when I have an example to go on.

**Comment by wicast** [comment]
https://github.com/effekseer/Effekseer
How about this one?

**Comment by nemerle** [comment]
As an example of what I was talking about, here's an APNG from one of my favourite games:
![coh_bubbly](https://user-images.githubusercontent.com/96597/44335858-fd252900-a475-11e8-81b2-844e49c254cf.png)
 
Steps that are used to render this:
1. Render the multi-geometry model to FBO+Stencil
1. Render the 'Effect' built from multiple particle systems, centered over the model.
1. Render the colored background over the model, using stencil to only fill non-model areas

Other approach would be to use stencil in step 2. to limit the drawing to the model's silhouette

**Comment by BearishSun** [comment]
It's a nice effect. I doubt I'm going to support this out of the box though. It feels like particle rendering would need a lot of extra code just for this specific effect, while I'm generally trying to keep things as generic as possible.

Ideally I want to expose enough of the renderer to the user so they can make effects like these on their own. Currently the particle shader can be provided by the user, meaning part of that job is done. You could potentially also use render queue priorities to force a mesh to draw before the particle system, filling up the stencil buffer, and then use the particle material to only draw in those areas.

That might be a stretch though. But that's the general idea I want to go in, and extend the API so these things are possible.

**Comment by BearishSun** [comment]
Feature implemented and ready for release with v1.1.
