### ISSUE TITLE
c++17 usage in the codebase.

### ISSUE THREAD

**Issue by nemerle** [GameFoundry/bsf#107]
It seems bsf is using a few c++17 features - nested namespaces for example.
Should those things be removed, or should we enable c++1z flag, and remove `-Wno-c++1z-extensions` from Apple xcode9 build ?

**Comment by BearishSun** [comment]
I want to keep the nested namespaces. Enabling the `c++1z` flag sounds good. Going forward I'll likely want it enabled for all platforms, as soon as I get a bit of time to test for any issues across all platforms.

**Comment by nemerle** [comment]
I'm doing a cmake PR in a few minutes anyway, so adding c++1z to Apple build and looking at CI output might be enough.

**Comment by BearishSun** [comment]
Closing as the PR was merged (manually).
