### ISSUE TITLE
the function “unload” in BsDynLibManager.cpp doesn't work properly

### ISSUE THREAD

**Issue by XMatrixXiang** [GameFoundry/bsf#111]
const auto& iterFind = mLoadedLibraries.find(lib->getName());
	if (iterFind != mLoadedLibraries.end())
	{
		mLoadedLibraries.erase(iterFind);
	}

the 'iterFind' always point to the end,so mLoadedLibraries.erase(iterFind) has no chance to execute！

**Comment by jonesmz** [comment]
Why would iterFind alway equal mLoadedLibraries.end() ?

**Comment by BearishSun** [comment]
Thanks for the report. One of the `operator<` methods got removed yesterday, as I assume it conflicted with the new member operator of `NPtr`, so comparisons are no longer being done properly.

@jonesmz Let me know if you have a clean way of resolving the issue.

**Comment by nemerle** [comment]
I think I have an idea, will PR soon
