### ISSUE TITLE
GUIInputBox character count is never updated outside of setText method

### ISSUE THREAD

**Issue by jayrulez** [GameFoundry/bsf#115]
This causes various issues using GUIInputBox.

E.g: If you set text to "Hello" using the setText method then you cannot delete (or backspace) and character at index outside the range of the original length.

**Comment by jayrulez** [comment]
While this fixes the issue, I would prefer a more elegant method where setText is always called to update the text so we do not have to worry about missing updating the character count in other places.

@BearishSun let me know what you think.

**Comment by BearishSun** [comment]
I wouldn't mind a more elegant solution if you feel like it (perhaps a simpler, internal version of `setText`).
