### ISSUE TITLE
undefined reference to `typeinfo for bs::GameObjectHandleBase'

### ISSUE THREAD

**Issue by scollon42** [GameFoundry/bsf#132]
Hi ! First, thank you for your awesome work. It's really great to find powerfull, opensource tool like this one to create and learn!
Maybe It's not the best place to put my problem, and if not I'm sorry and I would try on the support topic on Bs::Framework community forum.

I'm currently try to compile a first small application with bsf. 

- I'm using CMake on a Fedora 28x86_64
- cmake version 3.11.2
- compiler c++ (GCC) 8.1.1

I first build bsf from sources using CMake :
```sh
mkdir build && cd build
cmake ..
make
sudo make install
```
When I try to compile my small project the instances :
```cpp
	bs::HSceneObject sceneCameraSO;
	bs::HCamera sceneCamera;
```
Seems to create a compile error : `undefined reference to `typeinfo for bs::GameObjectHandleBase'`

I'm using a copy paste of the code from here : https://www.bsframework.io/docs/startup.html
If I don't create `sceneCameraSO `et `sceneCamera` it compile fine and I can run an emtpy window.

I don't know if I give enough informations. Don't hesitate to ask me more!
Thanks again

**Comment by scollon42** [comment]
Alright, 5minutes more research and I found my problem..
It seems that I needed to add `-fno-rtti` flag to my compiler.
to do so with CMake  add this line in your CMakeLists.txt : `add_compile_options(-fno-rtti)`

Sorry for bothering you! I close this issue :smile:

**Comment by BearishSun** [comment]
Glad you figured it out. I've updated the CMake code in the build manual to reflect the `-fno-rtti` flag requirement.

**Comment by scollon42** [comment]
I thought this morning I should have made a pull request with an add to the documentation.. Nice if you did it. Next time I'll. Thank for your awesome work.
