### ISSUE TITLE
"TARGET_PDB_FILE is not supported by the target linker."

### ISSUE THREAD

**Issue by Athomield** [GameFoundry/bsf#136]
I don't know why this happening. I'm using Mingw-W64 under Windows.

Here is the full error: 
    Built dependencies are out of date, forcing recompile.
Looking for snappy installation...
...snappy OK.
Looking for nvtt installation...
...nvtt OK.
Looking for OpenAL installation...
...OpenAL OK.
Looking for ogg installation...
...ogg OK.
Looking for vorbis installation...
...vorbis OK.
Looking for FLAC installation...
...FLAC OK.
Looking for PhysX installation...
...PhysX OK.
Looking for FBXSDK installation...
...FBXSDK OK.
Looking for freetype installation...
...freetype OK.
Looking for freeimg installation...
...freeimg OK.
Looking for XShaderCompiler installation...
...XShaderCompiler OK.
Configuring done
CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:bsf>

  TARGET_PDB_FILE is not supported by the target linker.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:bsfD3D11RenderAPI>

  TARGET_PDB_FILE is not supported by the target linker.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:bsfOpenAudio>

  TARGET_PDB_FILE is not supported by the target linker.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:bsfRenderBeast>

  TARGET_PDB_FILE is not supported by the target linker.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:bsfPhysX>

  TARGET_PDB_FILE is not supported by the target linker.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:bsfFBXImporter>

  TARGET_PDB_FILE is not supported by the target linker.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:bsfFontImporter>

  TARGET_PDB_FILE is not supported by the target linker.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:bsfFreeImgImporter>

  TARGET_PDB_FILE is not supported by the target linker.

CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:bsfSL>

  TARGET_PDB_FILE is not supported by the target linker.

Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    QT_QMAKE_EXECUTABLE

CMake Project parsing failed.

**Comment by BearishSun** [comment]
Hi. The build system was never configured for MinGW/Cygwin environments. In this particular case it was assuming it was running under MSVC just because it was on Windows. I've submitted a fix that hopefully resolves the issue.

But since this environment was never tested it's quite likely you'll run into other issues.

**Comment by Athomield** [comment]
Hi, I assumed that since it compiles on linux with GCC it will compile on Windows with MinGW with no issues. Thanks for the heads up anyway !

**Comment by Athomield** [comment]
Building still seems to fail. But since GCC is not meant to be supported on Windows, I'm closing this for now.
