### ISSUE TITLE
cannot make directory "C:/Program Files/bsf/bin//Data": No such file or directory           

### ISSUE THREAD

**Issue by Athomield** [GameFoundry/bsf#138]
When running cmake --build . --config Release --target install (after building with VS2017)
where the error happens : 
  setlocal                                                                                                                        "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake                                              if %errorlevel% neq 0 goto :cmEnd                                                                                               :cmEnd                                                                                                                          endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone                                                                       :cmErrorLevel                                                                                                                   exit /b %1                                                                                                                      :cmDone                                                                                                                         if %errorlevel% neq 0 goto :VCEnd                                                                                               :VCEnd                                                                                                                          -- Install configuration: "Release"                                                                                             -- Installing: C:/Program Files/bsf/bin//Data                                                                                   CMake Error at Source/cmake_install.cmake:36 (file):                                                                              file INSTALL cannot make directory "C:/Program Files/bsf/bin//Data": No                                                         such file or directory                                                                                                        Call Stack (most recent call first):                                                                                              cmake_install.cmake:37 (include)

**Comment by BearishSun** [comment]
It should work if you run the command with administrator permissions, or change the install folder somewhere off the system drive.

**Comment by Athomield** [comment]
Is the default install configurable through CMake or in the makefiles themselves ?

**Comment by BearishSun** [comment]
You can set the `CMAKE_INSTALL_PREFIX` through CMake. With makefiles you should also be able to set `DESTDIR`, but I don't think there is such an option for a VS build.

**Comment by Athomield** [comment]
Thanks !!
