### ISSUE TITLE
Lighting broken?

### ISSUE THREAD

**Issue by Pitj3** [GameFoundry/bsf#144]
I've been using the Framework since last night and so far I really enjoy using it. But when it comes to lighting, I get a bit confused by the results.

Created a small demo to explain what I mean:
https://hastebin.com/pedocepeca.cpp

In this I'm just using a simple Radial light, which already doesn't behave as expected. one of the triangles of the quad never gets lit, the shading is not what you would assume from a light at that position. (you'd assume the top of the cube to be lit, instead the bottom is lit? )

Here is a screencap of the application running:
https://i.imgur.com/9Z4f4CG.png

And a screencap of the console which has some stuff I get confused about as well:
https://i.imgur.com/yeuJ9j3.png

Is there just something I'm completely doing wrong?

I've tried directional lights as well, just can't get them to do what I want. Shadows not showing as well

**Comment by BearishSun** [comment]
Your code looks fine. The warnings in the console are also likely not the issue. The output does look wrong however.

Can you post your hardware, especially the GPU? Also are you using the latest version of the framework from the master branch or some other version?

**Comment by Pitj3** [comment]
I'm using the latest code of the master branch, running i7 8700K with a MSI GTX 1060 6GB ARMOR.

**Comment by BearishSun** [comment]
Thanks. Could you send over the `crate.jpg` and `ground.jpg` textures? Either that or send a screenshot using plain white textures. It makes it easier to compare if I can see the exact scene as you.

Also what is your nvidia driver version?
If you get a chance try compiling with the OpenGL render backend and see if there's any difference.

**Comment by Pitj3** [comment]
https://i.imgur.com/YIfvR9e.jpg
https://i.imgur.com/5NmtW0r.jpg

NVidia driver is: 390.65

Building with OpenGL requires a rebuild of the library with some cmake commands right?

**Comment by BearishSun** [comment]
You should be able to provide `-DRENDER_API_MODULE=OpenGL` to the cmake command line to toggle it. Or use CMake GUI and pick from a drop-down.

**Comment by Pitj3** [comment]
Running with OpenGL gives slightly better results, when enabling shadows the bottom of the cube is completely dark, still no actual shadows though.

https://i.imgur.com/l5DW4Sm.jpg

**Comment by BearishSun** [comment]
Thanks for trying with OpenGL. I think the shadows are there, it's just that the default skylight is pretty overpowering. You can try disabling indirect lighting on the Camera's RenderSettings object to disable sky lighting. However I'm seeing other issues with shadows on my end, heavy artifacts in this particular scene, but at least that's something I can reproduce.

Regarding the original issue though, could you try updating your drivers to `390.77`, or any later version. I'm on `390.77` so it stops me the hassle of downgrading so I can test with your `390.65` version, and I'd love to confirm this isn't a driver issue.

**Comment by Pitj3** [comment]
Just upgraded my drives and rebooted, same scene in opengl with the default skylight turned off:
https://i.imgur.com/q8RtKp8.jpg

You're a legend.

It was the indirect lighting that made it invisible to see. although I disabled that in DX before and didn't make the shadows appear. will try DX in a bit with the new drivers as well

**Comment by Pitj3** [comment]
DX: https://i.imgur.com/Gmbg3IJ.jpg without indirect lighting
with indirect: https://i.imgur.com/GuxexNw.jpg

Now properly renders, default skybox is very bright yes. So for DX the troubles were due to the driver

**Comment by BearishSun** [comment]
Awesome, glad it's resolved. I've also submitted a fix for the shadow artifact issue I've been seeing while testing with your scene - but I haven't seen it in your screenshots so I'm not sure you even had that problem.

Anyway, I do believe this is everything resolved so I'm closing the issue. Feel free to reopen if there are more problems.
