### ISSUE TITLE
Isolate CMake Flags for Parent Projects

### ISSUE THREAD

**Issue by cwfitzgerald** [GameFoundry/bsf#149]
When I add bsf in my project, it overwrites my flags and cause issues (I use exceptions and RTTI) as well as prevent me from getting some warnings. The flags need to be managed in a better way so flags are carried as needed (internal flags kept internal and external flags passed along). Changing to "linking" against targets that have the proper flags are the best and most modern solution to this.

I'll submit a PR once I've got a minute.

**Comment by BearishSun** [comment]
Yeah that's a good point, I haven't considered it until now. Adding the flags to targets is definitely the way to go.

**Comment by cwfitzgerald** [comment]
The Debug/OptimizedDebug/Release pattern is also causing problems as almost no one will expect you to change the defaults, and will cause a bunch of funky things to happen. The normal pair is `Debug/RelWithDebInfo/MinSizeRel/Release` which works fine with other libraries. I will probably split things up.

**Comment by cwfitzgerald** [comment]
As soon as I type this I realize why it's causing problems. Because I am including properties, it is changing CMAKE_CXX_FLAGS etc in my scope not yours (which is created with CMAKE_CXX_FLAGS). Investigating...

**Comment by BearishSun** [comment]
Closing this manually since #150 should have closed it automatically.
