### ISSUE TITLE
Int as array index

### ISSUE THREAD

**Issue by jonesmz** [GameFoundry/bsf#158]
In https://github.com/GameFoundry/bsf/blob/master/Source/Foundation/bsfCore/Components/BsCSliderJoint.cpp

Line 82.

```
void CSliderJoint::getLocalTransform(JointBody body, Vector3& position, Quaternion& rotation)
{
	position = mPositions[(int)body];
	rotation = mRotations[(int)body];

	HRigidbody rigidbody = mBodies[(int)body];
```

mPositions, mRotations, and mBodies are defined on line 134 in https://github.com/GameFoundry/bsf/blob/master/Source/Foundation/bsfCore/Components/BsCJoint.h

Shouldn't the array accesses be an unsigned type? I would expect

```
mBodies[(size_t)body];
```

Instead of int.

**Comment by BearishSun** [comment]
I guess unsigned type makes a bit more sense yeah, but ultimately I don't think it could have cause any issues. 'Fixed' in db6566158b56f2cbfc39888f21485f64fdea45ee.
