### ISSUE TITLE
Problem with spot light visibility

### ISSUE THREAD

**Issue by ivalduan** [GameFoundry/bsf#169]
I attach a simple scene to reproduce,
https://drive.google.com/open?id=1B-TpaYBMGAQj2R-QPQD7ViqZxHrE7i8b

Orbit the camera without moving and the light appears and disappears from view.

**Comment by BearishSun** [comment]
Thanks for the test case, it really makes things much easier.

This should be resolved with 4c0ceb44113c9a1a205383d6d3c7a7bc9c0aa846. Spot light bounds were just plain wrong, which manifested in a couple of ways - either the spot light would get culled when it shouldn't, or incorrect rendering technique would be used - both of which the end result was spot light not rendering.
