### ISSUE TITLE
Latest SceneManager changes breaks findComponent

### ISSUE THREAD

**Issue by ivalduan** [GameFoundry/bsf#171]
I am trying to use a component that depends on other component coexisting in the scene to work.
The second added component tries to find the first within onEnabled(), but this callback is called at the same time the components are created way before processStateChanges(), and the components list is empty.

This is bad I think. Shouldn't onEnabled be called only when the component becomes truly enabled for the SceneManager lists? That way components will be able to find other components added to the scene before inside onEnabled. Components have onInitialized to do previous stuff.

I can provide the Handle by hand to the component but we should be able to do it automatically. I guess the dumb solution is to do the findComponent on update instead of onEnabled but is it the only solution?

**Comment by BearishSun** [comment]
The reason why I went with this design is to avoid problems with components changing state within the callbacks themselves. For example a component could disable or destroy other components (or itself) during a call to `onEnabled`, which creates a lot of complications.

I'd need to re-check various component states after every callback, to ensure the list they were added to is actually still the list they belong to which adds a lot of extra work. 
Additionally when do I call `onDisabled` in the above case? What if `onDisabled` then re-enables the component? And that kind of weird stuff.

You can use `Utility::findComponents` for your purpose instead. I don't think `SceneManager::findComponents` would have suited your needs even before the change as it would have only found components enabled before the current component.

**Comment by ivalduan** [comment]
Sorry for bothering. `Utility::findComponents` seems just what I needed. You can close.
