### ISSUE TITLE
Trying to access a module but it hasn't been started up yet. BsModule.h:31

### ISSUE THREAD

**Issue by crookedbard** [GameFoundry/bsf#172]
### General info
- bsf version: current of 2018-07-05
- devices test on: macbook
- developing environments
   - Xcode version: Xcode version: Version 10.0 beta 2 (10L177m)

### Steps to Reproduce

1. build and run new app on xcode.
2. Crashes on this line in main.cpp:
// Initializes the application and creates a window with the specified properties
    bs::VideoMode videoMode(bs::windowResWidth, bs::windowResHeight);
    **bs::Application::startUp(videoMode, "Example", false);**
### Log

objc[7052]: Class BSPlatform is implemented in both /System/Library/PrivateFrameworks/BaseBoard.framework/Versions/A/BaseBoard (0x7fff9680dfe0) and /usr/local/lib/libbsf.dylib (0x100c4fa68). One of the two will be used. Which one is undefined.
2018-07-05 00:04:32.795695+0300 test-banshee[7052:270342] [DYMTLInitPlatform] platform initialization successful
A fatal error occurred and the program has to terminate!
  - Error: InternalErrorException
  - Description: Trying to access a module but it hasn't been started up yet.
  - In function: static T &bs::Module<bs::CoreApplication>::instance() [T = bs::CoreApplication]
  - In file: /Users/dkr/Documents/GitHub/bsf/Source/Foundation/bsfUtility/Utility/BsModule.h:31

Stack trace: 
0) 0   libbsf.dylib                        0x0000000100a337b6 _ZN2bs12CrashHandler13getStackTraceEv + 294: bs::CrashHandler::getStackTrace() + 294
1) 1   libbsf.dylib                        0x0000000100a170c6 _ZNK2bs12CrashHandler21logErrorAndStackTraceERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS_8StdAllocIcNS_8GenAllocEEEEESA_SA_SA_j + 822: bs::CrashHandler::logErrorAndStackTrace(std::__1::basic_string<char, std::__1::char_traits<char>, bs::StdAlloc<char, bs::GenAlloc> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, bs::StdAlloc<char, bs::GenAlloc> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, bs::StdAlloc<char, bs::GenAlloc> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, bs::StdAlloc<char, bs::GenAlloc> > const&, unsigned int) const + 822
2) 2   libbsf.dylib                        0x0000000100a332be _ZNK2bs12CrashHandler11reportCrashERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS_8StdAllocIcNS_8GenAllocEEEEESA_SA_SA_j + 14: bs::CrashHandler::reportCrash(std::__1::basic_string<char, std::__1::char_traits<char>, bs::StdAlloc<char, bs::GenAlloc> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, bs::StdAlloc<char, bs::GenAlloc> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, bs::StdAlloc<char, bs::GenAlloc> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, bs::StdAlloc<char, bs::GenAlloc> > const&, unsigned int) const + 14
3) 3   libbsf.dylib                        0x00000001005900cd _ZN2bs6ModuleINS_15CoreApplicationEE8instanceEv + 749: bs::Module<bs::CoreApplication>::instance() + 749
4) 4   libbsf.dylib                        0x000000010058fdd9 _ZN2bs16gCoreApplicationEv + 9: bs::gCoreApplication() + 9
5) 5   libbsf.dylib                        0x000000010066aae2 _ZN2bs5InputC2Ev + 1890: bs::Input::Input() + 1890
6) 6   libbsf.dylib                        0x000000010058c19f _ZN2bs6ModuleINS_5InputEE7startUpIJEEEvDpOT_ + 63: void bs::Module<bs::Input>::startUp<>() + 63
7) 7   libbsf.dylib                        0x00000001005893a6 _ZN2bs15CoreApplication9onStartUpEv + 358: bs::CoreApplication::onStartUp() + 358
8) 8   libbsf.dylib                        0x0000000100937d03 _ZN2bs11Application9onStartUpEv + 19: bs::Application::onStartUp() + 19
9) 9   test-banshee                        0x000000010001d1b7 _ZN2bs6ModuleINS_15CoreApplicationEE7startUpINS_11ApplicationEJRNS_13START_UP_DESCEEEEvDpOT0_ + 871: void bs::Module<bs::CoreApplication>::startUp<bs::Application, bs::START_UP_DESC&>(bs::START_UP_DESC&&&) + 871
10) 10  test-banshee                        0x000000010001313a _ZN2bs11Application7startUpIS0_EEvNS_9VideoModeERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS_8StdAllocIcNS_8GenAllocEEEEEb + 106: void bs::Application::startUp<bs::Application>(bs::VideoMode, std::__1::basic_string<char, std::__1::char_traits<char>, bs::StdAlloc<char, bs::GenAlloc> > const&, bool) + 106
11) 11  test-banshee                        0x0000000100013061 main + 225: main + 225
12) 12  libdyld.dylib                       0x00007fff687a8b11 start + 1: start + 1
(lldb)

**Comment by BearishSun** [comment]
Thanks for the report, I'll take a look when I get a chance to test on mac. Might be due to some recent Xcode changes.

**Comment by BearishSun** [comment]
Thanks for investigating. I'm not on Mac right now which is why I still haven't taken a proper look at this issue but could you perhaps try renaming `BSPlatform` to something else? (like `BSFPlatform`)

If you get a chance let me know if that works. (and ideally make a PR with the changes)

`bsf` does indeed only specify dependencies `CoreFoundation` and a few other select frameworks, but I don't think you can avoid linking with the SDK (and therefore the `BaseBoard.framework`). My knowledge might be lacking, so there might be a way to avoid it, but I'm not sure how. Renaming seems to be a safe call though.

**Comment by ondrowan** [comment]
It seems it worked. I created a PR. Lemme know if there's something more to add / change.
