### ISSUE TITLE
Math utility class do not have double support?

### ISSUE THREAD

**Issue by remoe** [GameFoundry/bsf#183]
I found your math classes (Vector, Matrix, Quaternion ... ) do not have double support. What is the reason?

**Comment by BearishSun** [comment]
There is no specific reason other than I didn't have the time to add it yet.

**Comment by jonesmz** [comment]
@remoe 

Why not open a PR to convert those classes to template classes, defaulting to float?

**Comment by remoe** [comment]
Ok, thanks. First i need to find time to try your very interesting framework ;)
