### ISSUE TITLE
Linux: bsfExamples trouble with bsfSL.so

### ISSUE THREAD

**Issue by nemerle** [GameFoundry/bsf#188]
I have some trouble running any of the built binaries:
`./CustomMaterials: symbol lookup error: libbsfSL.so: undefined symbol: _ZN3Xsc13IndentHandlerC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
`
which demangles to:
`Xsc::IndentHandler::IndentHandler(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)`
Perhaps the libxsc_core.a was compiled with 'old' gcc that did not tag c++11 strings properly ?

**Comment by BearishSun** [comment]
I think I compiled XShaderCompiler on Travis, which is likely using Ubuntu's package-provided GCC which I believe still uses old types by default. I have this fixed locally but haven't managed to push a fix today.

For now you can set `BS_FRAMEWORK_PREBUILT_DEPENDENCIES_VERSION` to `7` in https://github.com/GameFoundry/bsf/blob/master/Source/CMakeLists.txt and it should fetch new dependencies which I uploaded today, which should work.

**Comment by nemerle** [comment]
Will do, thank You :)
