### ISSUE TITLE
"Trying to access a resource when its not loaded" error

### ISSUE THREAD

**Issue by ethindp** [GameFoundry/bsf#191]
I have the 1.0.0 beta of BSF up and running. So far, anyway. I've decided to try and make a game with it and see how far I get. I was thinking I'd scale the game as BSF scaled. Here's my source code layout:
total 114
drwxr-xr-x   9 ethin Administrators  8192 Aug 27 13:39 .
drwxr-xr-x 125 ethin Administrators 65536 Aug 26 16:35 ..
-rw-r--r--   1 ethin Administrators  2016 Aug 27 23:45 CMakeLists.txt
-rw-r--r--   1 ethin Administrators  3205 Aug 26 14:28 Findbsf.cmake
drwxr-xr-x  22 ethin Administrators  8192 Aug 26 21:00 boost
drwxr-xr-x   5 ethin Administrators  4096 Aug 26 19:39 bsf
drwxr-xr-x  10 ethin Administrators 16384 Aug 27 23:50 build
drwxr-xr-x   2 ethin Administrators  4096 Aug 27 23:21 include
drwxr-xr-x   2 ethin Administrators     0 Aug 27 11:10 libs
drwxr-xr-x   2 ethin Administrators     0 Aug 27 23:19 src
drwxr-xr-x   8 ethin Administrators  4096 Aug 27 11:13 tolk
My source code, in regards to headers and source files, is as follows:

* include:
** audio.hpp
** bsAll.hpp
** menu.hpp
** tinyfiledialogs.h
** vars.hpp
* src:
** audio.cpp
** menu.cpp
** svm.cpp
** tinyfiledialogs.cpp

The error is:

Banshee Engine Log
System information
Banshee version: 0.4
OS version: Windows 10 64-bit
CPU vendor: GenuineIntel
CPU name: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
CPU clock speed: 2904Mhz
CPU core count: 4
GPU #0: Intel(R) HD Graphics 620
GPU #1: Microsoft Basic Render Driver
Log entries
Type
Description
Warning
Attempting to open a file that doesn't exist: c:\Users\ethin\source\svm\build\Data\Raw\DataList.json
in class std::shared_ptr __cdecl bs::FileSystem::openFile(const class bs::Path &,bool) [c:\projects\bsf\source\foundation\bsfutility\private\win32\bswin32filesystem.cpp:280]
Error
A fatal error occurred and the program has to terminate!
- Error: InternalErrorException
- Description: Trying to access a resource that hasn't been loaded yet.
- In function: void __cdecl bs::ResourceHandleBase::throwIfNotLoaded(void) const
- In file: c:\projects\bsf\source\foundation\bsfcore\resources\bsresourcehandle.cpp:123

Stack trace: 
0x140730078320230 Module[bsf.dll]
0x140730088975750 Module[bsf.dll]
0x140730093412902 Module[bsf.dll]
0x140730093402630 Module[bsf.dll]
0x140730093396975 Module[bsf.dll]
0x140730102518884 Module[bsf.dll]
0x140730102730926 Module[bsf.dll]
0x140730102731319 Module[bsf.dll]
0x140730101527136 Module[bsf.dll]
0x140730102534650 Module[bsf.dll]
0x140730102535386 Module[bsf.dll]
0x140730102411952 Module[bsf.dll]
0x140730102540215 Module[bsf.dll]
0x140730103349638 Module[bsf.dll]
0x140730102539795 Module[bsf.dll]
0x140730103451870 Module[bsf.dll]
0x140730103452686 Module[bsf.dll]
0x140730102167918 Module[bsf.dll]
0x140730104743111 Module[bsf.dll]
0x140730094906204 Module[bsf.dll]
wWinMain() - 0x140702629652973 File[svm.cpp:45 (0)] Module[svm.exe]
invoke_main() - 0x140702629705037 File[exe_common.inl:123 (0)] Module[svm.exe]
__scrt_common_main_seh() - 0x140702629704708 File[exe_common.inl:283 (5)] Module[svm.exe]
__scrt_common_main() - 0x140702629704398 File[exe_common.inl:326 (0)] Module[svm.exe]
wWinMainCRTStartup() - 0x140702629705177 File[exe_wwinmain.cpp:17 (0)] Module[svm.exe]
0x140732045406260 Module[KERNEL32.DLL]
0x140732084589617 Module[ntdll.dll]
I've bundled all the source code into a tar file at https://drive.google.com/file/d/15Lsy-OVIyHFuFmH8mHAmXHZEO6U-DN2P/view?usp=sharing. I've excluded boost, though -- you'll need 1.68.0 (you can alter if you like). A compiled executable is provided tough, with debugging symbols and all. I'm quite confused with this one. I'd use visual studio but it tries compiling for 32-bit and I can't figure out how to force CMake to generate 64-bit-only targets.

**Comment by BearishSun** [comment]
I just had the time to have a quick peek but I assume one of the resources you are importing fails to import. Possibly due to its file not being found due to working folder being different or something along those lines. I'd re-check the file paths.

If I get more time I'll try compiling the source but don't hold your breath on that one.

If you can get me a call-stack with file names/lines I can probably be more helpful.

**Comment by ethindp** [comment]
I think I've solved it. Its the warning ("Attempting to open a file
that doesn't exist:
c:\Users\ethin\source\svm\build\Data\Raw\DataList.json
in class std::shared_ptr __cdecl bs::FileSystem::openFile(const class
bs::Path &,bool)
[c:\projects\bsf\source\foundation\bsfutility\private\win32\bswin32filesystem.cpp:280]").
Its trying to load the GUI widget pictures but can't. I'll try adding
in the .json files again, but last time I did that it introduced
absurdly long loading times that were ridiculously high. Would that be
because its a debug build?

On 8/28/18, Marko Pintera <notifications@github.com> wrote:
> I just had the time to have a quick peek but I assume one of the resources
> you are importing fails to import. Possibly due to its file not being found
> due to working folder being different or something along those lines. I'd
> re-check the file paths.
>
> If I get more time I'll try compiling the source but don't hold your breath
> on that one.
>
> If you can get me a call-stack with file names/lines I can probably be more
> helpful.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/GameFoundry/bsf/issues/191#issuecomment-416708957


-- 
Signed,
Ethin D. Probst

**Comment by ethindp** [comment]
Yep, fixed it. One more question, unrelated to this issue, but still
(IMO) relevant to BSF: how would I go about making it possible to use
the keyboard and gamepad with the GUI? For example, my menu class
defines a GUI with a GUILayoutY, a list box with menu options, and two
buttons. In the stable version I don't have the GUINavGroup. How would
I implement this functionality without having to entirely rewrite the
GUI display system?

On 8/28/18, Ethin Probst <harlydavidsen@gmail.com> wrote:
> I think I've solved it. Its the warning ("Attempting to open a file
> that doesn't exist:
> c:\Users\ethin\source\svm\build\Data\Raw\DataList.json
> in class std::shared_ptr __cdecl bs::FileSystem::openFile(const class
> bs::Path &,bool)
> [c:\projects\bsf\source\foundation\bsfutility\private\win32\bswin32filesystem.cpp:280]").
> Its trying to load the GUI widget pictures but can't. I'll try adding
> in the .json files again, but last time I did that it introduced
> absurdly long loading times that were ridiculously high. Would that be
> because its a debug build?
>
> On 8/28/18, Marko Pintera <notifications@github.com> wrote:
>> I just had the time to have a quick peek but I assume one of the
>> resources
>> you are importing fails to import. Possibly due to its file not being
>> found
>> due to working folder being different or something along those lines. I'd
>> re-check the file paths.
>>
>> If I get more time I'll try compiling the source but don't hold your
>> breath
>> on that one.
>>
>> If you can get me a call-stack with file names/lines I can probably be
>> more
>> helpful.
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/GameFoundry/bsf/issues/191#issuecomment-416708957
>
>
> --
> Signed,
> Ethin D. Probst
>


-- 
Signed,
Ethin D. Probst

**Comment by BearishSun** [comment]
You could use normal input handling, `GUIElement::setFocus()` to change the focus, and `GUIElement::getBounds()` to determine the next element to set focus on.
