### ISSUE TITLE
Possible bug in `Importer::importAsync`

### ISSUE THREAD

**Issue by nemerle** [GameFoundry/bsf#192]
* `importAsync` calls `queueForImport` with a reference to a local `output`
* `Importer::queueForImport` uses `op`  as a constructor parameter for `QueuedOperation`
* but `QueuedOperation` only uses `op` by `const &`, and `op` is not modified 
* the function returns without modifying `op` anywhere else
* so the value returned by `importAsync` is always default-initialized `output`

**Comment by BearishSun** [comment]
This should be resolved with https://github.com/GameFoundry/bsf/commit/27404aa408db1f6f70ddd6c9b528fa4263473793.
