### ISSUE TITLE
GUINavGroup - how to use?

### ISSUE THREAD

**Issue by ethindp** [GameFoundry/bsf#193]
So I managed to fix my previous issue (issue #190). I've upgraded my copy of BSF to the July 31, 2018 snapshot. I was interested in GUINavGroup, and this one had it, so that's why. It also majorly improved loading speeds too. :) I'm curious though -- how would I use the GuINavGroup? It returns an SPtr, but I can't figure out how to add GUI elements to it, or to add it to a GUI layout. So am I missing something?

**Comment by BearishSun** [comment]
Try `GUIElement::setNavGroup`. In general please prefer to ask all questions on discourse.bsframework.io, while bug reports and (sometimes) feature requests belong here.
