### ISSUE TITLE
Precompiled binaries on OSX dylib not found

### ISSUE THREAD

**Issue by Milerius** [GameFoundry/bsf#194]
Hello i got this error:

<img width="729" alt="capture d ecran 2018-09-15 a 07 58 36" src="https://user-images.githubusercontent.com/21139416/45583167-31490980-b8bd-11e8-95f1-40496e0aa802.png">

with minimal configuration:

<img width="661" alt="capture d ecran 2018-09-15 a 07 59 12" src="https://user-images.githubusercontent.com/21139416/45583169-4a51ba80-b8bd-11e8-833a-a5ed682549bf.png">
<img width="919" alt="capture d ecran 2018-09-15 a 07 59 19" src="https://user-images.githubusercontent.com/21139416/45583170-4a51ba80-b8bd-11e8-94d8-ed71f52a36fa.png">

<img width="1173" alt="capture d ecran 2018-09-15 a 08 01 33" src="https://user-images.githubusercontent.com/21139416/45583192-a0266280-b8bd-11e8-9cb1-2c0391593396.png">

May be i do something wrong?

**Comment by Milerius** [comment]
After installing ossp-uuid with homebrew -> brew install ossp-uuid (should be marked in your documentation somewhere because i didn't have it defaultly installed)

I got a sigsegv -> 
<img width="416" alt="capture d ecran 2018-09-15 a 08 04 30" src="https://user-images.githubusercontent.com/21139416/45583211-fe534580-b8bd-11e8-8d98-17e10d50d51e.png">

<img width="1680" alt="capture d ecran 2018-09-15 a 08 05 09" src="https://user-images.githubusercontent.com/21139416/45583219-1aef7d80-b8be-11e8-8c3d-a79296fee6ea.png">

I have no debug information since i use the precompiled binaries, should i build manually on bsf on OSX or it's supposed to work ?

**Comment by Milerius** [comment]
I'm not using xcode I'm using clang 6.0 ! This is may be the problem ?

**Comment by BearishSun** [comment]
Building with Clang is fine - internally it will still use frameworks that ship with XCode though, so your builds can still be affected by version of XCode installed, even if you aren't using it directly.

Indeed I have not released a new version since that issue was resolved, that's why it works from source.

**Comment by Milerius** [comment]
Ok so can we close it, or you will close it when you will release a new osx precompiled version on the download page (because the fact is that doesn't work if we use the current download)

**Comment by Milerius** [comment]
Also you have some warnings -> 
<img width="1621" alt="capture d ecran 2018-09-15 a 12 45 37" src="https://user-images.githubusercontent.com/21139416/45585496-8ac52e80-b8e5-11e8-8411-5241756cc6ba.png">
<img width="1387" alt="capture d ecran 2018-09-15 a 12 46 25" src="https://user-images.githubusercontent.com/21139416/45585497-8ac52e80-b8e5-11e8-854d-ad6e1255bce3.png">
<img width="1225" alt="capture d ecran 2018-09-15 a 12 46 41" src="https://user-images.githubusercontent.com/21139416/45585498-8ac52e80-b8e5-11e8-8e31-7d817290c7d3.png">
<img width="1494" alt="capture d ecran 2018-09-15 a 12 46 56" src="https://user-images.githubusercontent.com/21139416/45585499-8b5dc500-b8e5-11e8-9ae7-be3dbf671ba4.png">

**Comment by BearishSun** [comment]
On latest master LibUUID should no longer require to be separately installed.
