### ISSUE TITLE
Confusing bs::SceneObject/Components transform duplication

### ISSUE THREAD

**Issue by nemerle** [GameFoundry/bsf#196]
We create a light:
```cpp
HSceneObject lightSO = SceneObject::create("Light");
HLight light = lightSO->addComponent<CLight>();
```
now we do:
```cpp
lighSO->setPos({-1,0,0});
bs::Transform tf;
tf.setPosition({1,0,0})
light->_getLight()->setTransform(tf);
```
So have we set two positions on a single light ? 
I think it's pretty confusing that `Component` such as Light or CAudioListener have embedded in themselves a whole other transform, independent from the SceneObject they are a part of.

Is my understanding incorrect, are Components in bsf not meant to be modeled after ECS components ?

**Comment by BearishSun** [comment]
In `bsf` components act as wrappers around lower level objects. Those lower level objects can then be implemented efficiently in their own systems, without needing to have an overhead or even the knowledge of the component system. Components usually require additional code and this approach cleanly separates the two. As an extra bonus it allows the whole framework to be used in a way without components.

Note that in your case `_getLight()` is an internal method and should not be called by normal users (as stuff will break unless used in a specific manner, as you have shown). Normally the SceneObject transform changes will get transfered to the underlying object, as the system deems necessary. This duplication could ultimately be eliminated, but probably be wont until profiling shows its impact is relevant.

**Comment by nemerle** [comment]
Thanks for explaining :)
