### ISSUE TITLE
Build failure with clang 7.0

### ISSUE THREAD

**Issue by Milerius** [GameFoundry/bsf#198]
Hello it's seem's that the engine doesn't compile with clang 7.0

<img width="1568" alt="capture d ecran 2018-09-23 a 15 58 52" src="https://user-images.githubusercontent.com/21139416/45928801-b7162600-bf49-11e8-86bb-d22c95b7af9b.png">

If you are aware of this problem let me know, (it's seem's that the problem is from nlohmann-json, we can try to update dependancies to see what happen)

**Comment by Milerius** [comment]
I can confirm that the pr #199 fix the compilation, let's wait for the CI.

**Comment by BearishSun** [comment]
Closing as the PR was merged.
