### ISSUE TITLE
copyToMemory in BsWin32RenderWindow not needed?

### ISSUE THREAD

**Issue by remoe** [GameFoundry/bsf#210]
In file https://github.com/GameFoundry/bsf/blob/master/Source/Plugins/bsfVulkanRenderAPI/Win32/BsWin32RenderWindow.h

it has a method "void copyToMemory(PixelData &dst, FrameBuffer buffer);" which are not implemented in 

https://github.com/GameFoundry/bsf/blob/master/Source/Plugins/bsfVulkanRenderAPI/Win32/BsWin32RenderWindow.cpp

**Comment by BearishSun** [comment]
Indeed, that can be removed. Feel free to make a PR or I'll make the change in one of my next commits.
