### ISSUE TITLE
dev question: how does the crash handler work for MacOSX?

### ISSUE THREAD

**Issue by remoe** [GameFoundry/bsf#215]
How does BSF catch crashes on MacOSX? I don't find any function like:
catch_mach_exception_raise_state or mach_excServer.c

? :)

**Comment by BearishSun** [comment]
It catches signals, see `BsUnixCrashHandler.cpp`.  It's not my primary OS so I'm not aware of intricacies of its error handling, but if there's a better macOS specific way to do it, I'd consider adding it.

**Comment by remoe** [comment]
Thanks. I wonder why that this works ;)

**Comment by remoe** [comment]
Here is a link to how mach exception handler works:

https://www.mikeash.com/pyblog/friday-qa-2013-01-11-mach-exception-handlers.html

On an app i develop i used signals as well, but this doesn't prevent the default crash handler of MacOSX to pop up. So, i wonder why this work on your framework.

**Comment by BearishSun** [comment]
Do you know what determines with the apple crash reporter pops up? I'm assuming it then eats the signals? Did you experience issues with `bsf` where a crash wasn't properly handled?

**Comment by remoe** [comment]
I didn't not find any issue during debugging of ```bsf``` with the crash handler.

**Comment by BearishSun** [comment]
It might be nice to support Mach error handling, especially if it provides nicer error messages. Some of the crashes triggered from objC can be confusing. Although it's not a high priority for me.
