### ISSUE TITLE
libbsf.dylib ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by whitespeed** [GameFoundry/bsf#222]
Undefined symbols for architecture x86_64:
  "bs::SmallVector<bs::ShaderVariation::Param, 4u>::~SmallVector()", referenced from:
      bs::ShaderVariation const& bs::ct::DebugDrawMat::getVariation<true, false, false>() in BsDebugDraw.o
      bs::ShaderVariation const& bs::ct::DebugDrawMat::getVariation<false, false, true>() in BsDebugDraw.o
      bs::ShaderVariation const& bs::ct::DebugDrawMat::getVariation<false, true, false>() in BsDebugDraw.o
      bs::ShaderVariation const& bs::ct::BlitMat::getVariation<2u, true>() in BsRendererUtility.o
      bs::ShaderVariation const& bs::ct::BlitMat::getVariation<4u, true>() in BsRendererUtility.o
      bs::ShaderVariation const& bs::ct::BlitMat::getVariation<8u, true>() in BsRendererUtility.o
      bs::ShaderVariation const& bs::ct::BlitMat::getVariation<2u, false>() in BsRendererUtility.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by whitespeed** [comment]
Use Xcode 10.1 macOS Mojave 10.14

**Comment by whitespeed** [comment]
On branch master first pull and compile.

**Comment by BearishSun** [comment]
Can you try re-running CMake before compiling and see if the issue still happens?

**Comment by whitespeed** [comment]
I try again, but still same error .......

**Comment by BearishSun** [comment]
This should be resolved on latest.
