### ISSUE TITLE
Any possibility of a C-exported API?

### ISSUE THREAD

**Issue by VioletasTheThird** [GameFoundry/bsf#231]
Would it ever be a possibility of a C API for this? I don't know how possible this would actually be, since I haven't got the time to look through the codebase, but I feel like it would be nice as it would open up use to a plethora of different languages rather than just C++. I understand if this is not possible

**Comment by BearishSun** [comment]
The framework uses code generation to generate API for other languages. Currently only C# output is supported, but a C one is also possible. That said I have no plans on adding C support myself, it would have to be a contributor.

In the future please use discourse.bsframework.io for questions.

**Comment by VioletasTheThird** [comment]
Ah ok, I understand (sorry for the late follow up lmao)
