### ISSUE TITLE
Materials do not load correctly (Textures in wrong slot?)

### ISSUE THREAD

**Issue by ataulien** [GameFoundry/bsf#244]
There seems to be a problem with deserializing materials: I'm generating a material by hand, then save it, then load it again straight away:

```cpp
HMaterial m = Material::create(shader);
m->setTexture("gAlbedoTex", albedo);

const bool overwrite = false;
gResources().save(m, materialPath, overwrite);

HMaterial loaded = gResources().load<Material>(materialPath);
```

Even though it loads the same file I just wrote, I get the following log-output:
```
Unknown version. Unable to deserialize.
		 in unsigned int __cdecl bs::RTTIPlainType<struct bs::MaterialParamsRTTI::MaterialParam>::fromMemory(struct bs::MaterialParamsRTTI::MaterialParam &,char *) [F:\Code\bsfExamples\bsf\Source\Foundation\bsfCore\Private/RTTI/BsMaterialParamsRTTI.h:450]
```

This is the function which throws the error while processing an element named `gEmissiveColor`:
```cpp
static UINT32 fromMemory(MaterialParamsRTTI::MaterialParam& data, char* memory)
{ 
	UINT32 size = 0;
	UINT32 sizeRead = 0;
			
	memory = rttiReadElem(size, memory, sizeRead);
	memory = rttiReadElem(data.name, memory, sizeRead);
	memory = rttiReadElem(data.data, memory, sizeRead);

	// More fields means a newer version of the data format
	if(size > sizeRead)
	{
		UINT32 version = 0;
		memory = rttiReadElem(version, memory);

		switch (version)
		{
		case 1:
			memory = rttiReadElem(data.index, memory);
			break;
		default:
			LOGERR("Unknown version. Unable to deserialize.");
			break;
		}
	}
	else
		data.index = (UINT32)-1; // Lets the other code know that index needs to be generated

	return size;
}
```

Here is a piece of the hexdump of the file I'm trying to load:
![image](https://user-images.githubusercontent.com/11406580/50667494-d9442900-0fb9-11e9-8646-66877d3bee01.png)

Am I doing something wrong here?

**Comment by ataulien** [comment]
Sorry, I've just seen https://discourse.bsframework.io/t/error-while-decoding-a-material/346.
I'll check the latest master version tomorrow and report back!

**Comment by ataulien** [comment]
The Material will load on the latest master, but it seems like not all properties are loaded correctly.

For example, here is the mesh of a sheep, right after importing:
![image](https://user-images.githubusercontent.com/11406580/50691780-046a5f00-1032-11e9-93c2-8f978db1e2ea.png)

The a prefab of the sheep-object and all resources are then saved to disk.
This is what it looks like when said prefab is loaded again:
![image](https://user-images.githubusercontent.com/11406580/50691897-6fb43100-1032-11e9-9b89-3fd884421e5e.png)

As you can see, the texture is still there, but it may went to the wrong slot?
I'm using the standard shader and I'm only setting the Albedo texture so far...

**Comment by christianclavet** [comment]
Strange, looking at the results, it look that the shading gone from black to white (invert effect). Might be a issue with the shader itself or the **way the shader is fed** (Serialisation issue?). I don't think it went in the wrong slot as this clearly look like a shading issue and you are only using the albedo|diffuse slot.

Emissivematerial should affect the shading, but not this way (revert). It really look like the shading had decided to use white instead of black values.

**Comment by BearishSun** [comment]
Indeed, parameter order wasn't properly maintained. Thanks for helping tracking it down. I submitted a fix in 359ba1c2dfe0519464db60ca55d8f63b72aceec4.

**Comment by BearishSun** [comment]
I'll close this since everything appears fine in my tests. Feel free to reopen if there are still issues.

**Comment by ataulien** [comment]
Oh, sorry, I forgot to report back. The issue is indeed fixed for me as well.
