### ISSUE TITLE
Performance issue - Low fps

### ISSUE THREAD

**Issue by ErrorFlexXx** [GameFoundry/bsf#246]
Hello,

I wrote a small fps counter and created a program, that just constructs a SceneCamera and this FPSLogger component. Located here: https://github.com/ErrorFlexXx/BsZenLib/blob/fpsViewer/samples/clear-scene.cpp

If I run this scene, with basically nothing to display, in 1080p fullscreen mode, I get stable 22 fps.
But only, with setMSAACount(1). With MSAACount(4) it is at 10 fps.
While running this, the gpu is utilized with 98 % and one cpu core stays at 100%.

Am I missing something or can I try something to debug this or speed it up ?
This would be very nice, because this framework looks quite powerful :+1: 

### Further informations:

OS: Ubuntu 18.04.1
Driver: NVidia 390.77
Graphic card: GeForce GTX750ti
CPU: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
bsf-version: latest commit from 30. december ebf3a188d10df5f85fb6d0ddf8834f7ae147392a

**Comment by ErrorFlexXx** [comment]
Wow.

So I changed `BsRenderBeast` to
```cpp
void RenderBeast::initializeCore()
{
[...]
/*    if(
    !rapiInfo.isFlagSet(RenderAPIFeatureFlag::Compute) ||
    !rapiInfo.isFlagSet(RenderAPIFeatureFlag::LoadStore) ||
    !rapiInfo.isFlagSet(RenderAPIFeatureFlag::TextureViews)) */
    {
        mFeatureSet = RenderBeastFeatureSet::DesktopMacOS;
    }
[...]
```

and get immediately 60 fps, even with a displayed mesh.
Impressive ^^
Many thanks! :+1: 

Are there plans to some how auto detect such situations and use a better fitting feature set then ?

**Comment by BearishSun** [comment]
Auto-detection probably isn't on the horizon at this point, but we should add a way to allow the user to toggle these on-off manually (without having to edit the code). There will be more options in the future, and even lower end rendering paths.

**Comment by christianclavet** [comment]
ErrorFleXx are you sure your running from the NVidia card? Looking at your report, it almost look like you plugged the screen on the integrated intel chip. Is the driver on the NVidia is installed correctly? (Using the driver from NVidia or "Nouveau"?)
