### ISSUE TITLE
Scene-Object transformation not working once an animation clip is played

### ISSUE THREAD

**Issue by ataulien** [GameFoundry/bsf#254]
I have a Scene-Object with Renderable and Animation Components.

Since the mesh is too big for the scene, I scaled it down a bit. I also have the Object-Rotator component from the example projects attached to it.

Both stop working once I call `CAnimation::play`. The model is rendered too big again and the rotation snaps back and can't be modified anymore.

Could it be that the scene objects world matrix is not multiplied to the final result of the skeletal animation? Unfortunately I couldn't find the shader or code which does the skinning...

**Comment by BearishSun** [comment]
The way it's set up currently is that the animation root scene object will inherit the transform from the animation root bone, overriding the existing transform. There might eventually be a toggle to make this optional, but for now I suggest you set up a parent scene object with your manual transform instead.

**Comment by ataulien** [comment]
That works!

I don't think an option is needed because an option will likely collide with root motion anyways. Maybe put a hint-box into the documentation on how to play animations?

**Comment by BearishSun** [comment]
I'll add a hint in the docs.
