### ISSUE TITLE
GUI Element Depth/Z is weird

### ISSUE THREAD

**Issue by webhaikal** [GameFoundry/bsf#256]
The GUI Elements such as a label or button would sometimes draw behind another object thus I can't see it but can still interact with it. Is there a way to circumvent this?

**Comment by BearishSun** [comment]
By other object I assume you mean other GUI element. And by interact I assume you mean by mouse.

Generally elements such as buttons and others that react to mouse input will block input to any elements with higher depth. Others like labels will let the input through. 

There is a `GUIElementOption::ClickThrough` option that can be used to force such elements to pass the input through. I don't believe this flags works in the reverse case - forcing non-input elements to block input, but that can probably be easily implemented.

You can also create a background blocker element. Either by creating a fake button element, or creating a custom GUIElement that eats mouse input.

**Comment by webhaikal** [comment]
I may have worded it wrong based on what you've responded. The elements I have on screen currently is just a button and a texture background. The background would sometimes be of higher depth than the button thus hiding the button from view.

**Comment by BearishSun** [comment]
In that case, you need to make sure to place your elements on different `GUIPanel` objects. Each panel can have its own depth.
