### ISSUE TITLE
gEmissiveMaskSamp is aliased as gMetalnessTex

### ISSUE THREAD

**Issue by xKamuna** [GameFoundry/bsf#261]
Is this intended?: https://github.com/GameFoundry/bsf/blob/3990632900f00f6b5e1898e49bb0fdd79eabd40c/Data/Raw/Shaders/Diffuse.bsl#L23

It happens in multiple files as well.

**Comment by BearishSun** [comment]
Doesn't look like it's intended, thanks. I'll take care of it.

**Comment by BearishSun** [comment]
Fixed in b482e7b93a0f1b8f943a625880ebf738eb08e8fc
