### ISSUE TITLE
Enable rtti?

### ISSUE THREAD

**Issue by unclejimbo** [GameFoundry/bsf#262]
Hi, I'd like to use bsf with other 3rd-party libraries which require rtti on. I think maybe it's better to offer an option to enable rtti in CMake while configuring and compiling bsf? Since I'm using the imported target bsf::bsf and it automatically set the compile options with -fno-rtti.

**Comment by BearishSun** [comment]
I'd be fine with making it optional through a CMake property, if you wanted to make a PR.

**Comment by mworchel** [comment]
Just stumbled upon this issue. It's resolved by #375, isn't it?

**Comment by BearishSun** [comment]
Yup. Closing.
