### ISSUE TITLE
MIT vs. LGPL v3

### ISSUE THREAD

**Issue by kingofoz** [GameFoundry/bsf#263]
Hi @BearishSun 
Looks Banshee3D is under LGPL v3 license, and bsf is under MIT license. I think bsf is the core of Banshee3D. Will the two licenses conflict with each other?

Thanks,
Yingjun

**Comment by BearishSun** [comment]
There is no conflict as far as I am aware of, MIT is a very open license.

For future questions please use the forums, as @jayrulez said. Thanks.

**Comment by kingofoz** [comment]
Thanks. Please see https://discourse.bsframework.io/t/should-i-open-source-my-code-if-i-statically-link-bsf/361
