### ISSUE TITLE
Anyone passed the compiling in windows + cmake3.14？

### ISSUE THREAD

**Issue by CharlesHo110** [GameFoundry/bsf#290]

**Comment by BearishSun** [comment]
I haven't tried with CMake 3.14. Are you getting a specific error?

**Comment by jayrulez** [comment]
I used 3.14 without issue.

**Comment by CharlesHo110** [comment]
The C compiler identification is MSVC 19.16.27027.1
The CXX compiler identification is MSVC 19.16.27027.1
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Fetching 'bsf' submodule...
Binary dependencies for 'bsf' are missing. Downloading package...
[download 0% complete]
[download 1% complete]
[download 2% complete]
[download 3% complete]
[download 4% complete]
[download 5% complete]
[download 6% complete]
[download 7% complete]
[download 8% complete]
[download 9% complete]
[download 10% complete]
[download 11% complete]
[download 12% complete]
[download 13% complete]
[download 14% complete]
[download 15% complete]
[download 16% complete]
[download 17% complete]
[download 18% complete]
[download 19% complete]
[download 20% complete]
[download 21% complete]
[download 22% complete]
[download 23% complete]
[download 24% complete]
[download 25% complete]
[download 26% complete]
[download 27% complete]
[download 28% complete]
[download 29% complete]
[download 30% complete]
[download 31% complete]
[download 32% complete]
[download 33% complete]
[download 34% complete]
[download 35% complete]
[download 36% complete]
[download 37% complete]
[download 38% complete]
[download 39% complete]
[download 40% complete]
[download 41% complete]
[download 42% complete]
[download 43% complete]
[download 44% complete]
[download 45% complete]
[download 46% complete]
[download 47% complete]
[download 48% complete]
[download 49% complete]
[download 50% complete]
[download 51% complete]
[download 52% complete]
[download 53% complete]
[download 54% complete]
[download 55% complete]
[download 56% complete]
[download 57% complete]
[download 58% complete]
[download 59% complete]
[download 60% complete]
[download 61% complete]
[download 62% complete]
[download 63% complete]
[download 64% complete]
[download 65% complete]
[download 66% complete]
[download 67% complete]
[download 68% complete]
[download 69% complete]
[download 70% complete]
CMake Error at bsf/Source/CMake/HelperMethods.cmake:283 (message):
  Binary dependencies failed to download from URL:
  https://data.banshee3d.com/bsfDependencies_VS2015_Master_8.zip
Call Stack (most recent call first):
  bsf/Source/CMake/HelperMethods.cmake:307 (update_binary_deps)
  bsf/Source/CMakeLists.txt:53 (check_and_update_binary_deps)


Configuring incomplete, errors occurred!
See also "E:/bsfExamples/Build/CMakeFiles/CMakeOutput.log".

@BearishSun

**Comment by ataulien** [comment]
I had the dependency download fail on my for several times as well but when building the editor. I ended up downloading the package using a browser, which was pretty slow but worked... So this seems to be more of a network related issue?

@CharlesHo110 Make sure to put important information like the error log into the initial post next time. Every piece of information helps if you want your issue to be resolved quickly.

Since you were asking about cmake 3.14 specifically, does it work with other versions then?

**Comment by CharlesHo110** [comment]
@ataulien I just tried the old version while it told me that I should use the version which is higher than 3.12.
I will try to download it myself in browser.Maybe it is useful.Actually I just want to glance over bsf's render architecture.

**Comment by ataulien** [comment]
You can get complete binary builds from here: https://www.bsframework.io/download.html

Should be easier than manually getting the dependency file.

**Comment by CharlesHo110** [comment]
I generated the projects file finally by download the dependencies by browser. I think there is bug in the cmake's download system.It always failed in weak connection. Thank you so much. @ataulien

**Comment by BearishSun** [comment]
Glad you have it resolved. I've opened a new issue regarding this, https://github.com/GameFoundry/bsf/issues/291. Hopefully we can move the dependencies to a server with better connectivity around the world.
