### ISSUE TITLE
How to build other renderApi version? 

### ISSUE THREAD

**Issue by CharlesHo110** [GameFoundry/bsf#292]
I can not find the way to change to other RenderApi,It seems I have to build the project again.
By the way,why don't you design it to a dynamic render? There exist render switch requirement in a platform such as android or ios.

**Comment by BearishSun** [comment]
You can set the render backend to use through [http://docs.bsframework.io/latest/structbs_1_1_s_t_a_r_t___u_p___d_e_s_c.html](START_UP_DESC) and pass it along to `Application` on start-up.

In the future please post questions on discourse.bsframework.io, we're keeping this section for bug reports and feature requests only.
