### ISSUE TITLE
Crashing for the low level render in windows while change to OpenGL Render Module

### ISSUE THREAD

**Issue by CharlesHo110** [GameFoundry/bsf#298]
Vulkan is crashing too.

os: win7 
example: low level render
render module: openGL
bsf version: master

Error | 17:14:53 | A fatal error occurred and the program has to terminate!- Error: RenderingAPIException- Description: OpenGL error: SHADER_ID_COMPILE error has been generated. GLSL compile failed for shader 2, "": ERROR: 0:5: '' : incorrect GLSL version: 450WARNING: 0:9: 'GL_ARB_explicit_attrib_location' : extension is not available in current GLSL versionWARNING: 0:9: 'local_size_x' : symbol not available in current GLSL version WARNING: 0:9: 'local_size_y' : symbol not available in current GLSL version WARNING: 0:9: 'local_size_z' : symbol not available in current GLSL version WARNING: 0:14: 'function' : is not available in current GLSL version groupMemoryBarrierWARNING: 0:15: 'function' : is not available in current GLSL version barrierWARNING: 0:17: 'uint' : symbol not available in current GLSL version WARNING: 0:128: 'GL_ARB_explicit_attrib_location' : extension is not available in current GLSL versionWARNING: 0:128: 'std430' : symbol not available in current GLSL version WARNING: 0:128: 'buffer' : symbol not available in current GLSL version ERROR: 0:131: 'array without size' : supported in geometry shaders only WARNING: 0:133: 'GL_ARB_explicit_attrib_location' : extension is not available in current GLSL versionWARNING: 0:133: 'std140' : symbol not available in current GLSL version WARNING: 0:135: 'uint' : symbol not available in current GLSL version WARNING: 0:136: 'uint' : symbol not available in current GLSL version WARNING: 0:137: 'uvec2' : symbol not available in current GLSL version WARNING: 0:140: 'shared' : symbol not available in current GLSL version WARNING: 0:150: 'uvec2' : symbol not available in current GLSL version WARNING: 0:? : 'variable' : is not available in current GLSL version gl_GlobalInvocationIDWARNING: 0:151: 'uvec2' : symbol not available in current GLSL version WARNING: 0:151: 'uvec2' : symbol not available in current GLSL version WARNING: 0:152: 'uint' : symbol not available in current GLSL version WARNING: 0:154: 'uint' : symbol not available in current GLSL version WARNING: 0:164: 'function' : is not available in current GLSL version textureLodWARNING: 0:164: 'assign' : implicit type conversion allowed from GLSL 1.20 WARNING: 0:? : 'variable' : is not available in current GLSL version gl_LocalInvocationIndexWARNING: 0:174: '>>=' : symbol not available in current GLSL version WARNING: 0:? : 'variable' : is not available in current GLSL version gl_LocalInvocationIndexWARNING: 0:176: 'uint' : symbol not available in current GLSL version WARNING: 0:? : 'variable' : is not available in current GLSL version gl_LocalInvocationIndexWARNING: 0:? : 'variable' : is not available in current GLSL version gl_LocalInvocationIndexWARNING: 0:178: 'uint' : symbol not available in current GLSL version WARNING: 0:? : 'variable' : is not available in current GLSL version gl_LocalInvocationIndexWARNING: 0:? : 'variable' : is not available in current GLSL version gl_LocalInvocationIndexWARNING: 0:179: 'uint' : symbol not available in current GLSL version WARNING: 0:? : 'variable' : is not available in current GLSL version gl_LocalInvocationIndexWARNING: 0:? : 'variable' : is not available in current GLSL version gl_LocalInvocationIndexWARNING: 0:180: 'uint' : symbol not available in current GLSL version WARNING: 0:? : 'variable' : is not available in current GLSL version gl_LocalInvocationIndexWARNING: 0:? : 'variable' : is not available in current GLSL version gl_LocalInvocationIndexWARNING: 0:181: 'uint' : symbol not available in current GLSL version WARNING: 0:? : 'variable' : is not available in current GLSL version gl_LocalInvocationIndexWARNING: 0:187: 'uint' : symbol not available in current GLSL version WARNING: 0:188: 'uint' : symbol not available in current GLSL version WARNING: 0:? : 'variable' : is not available in current GLSL version gl_WorkGroupIDWARNING: 0:? : 'variable' : is not available in current GLSL version gl_WorkGroupID- In function: void __cdecl bs::ct::openGlErrorCallback(unsigned int,unsigned int,unsigned int,unsigned int,int,const char *,void *)- In file: e:\bsfexamples\bsf\source\plugins\bsfglrenderapi\bsglrenderapi.cpp:2769Stack trace: bs::CrashHandler::reportCrash() - 0x8790962297190 File[bswin32crashhandler.cpp:468 (0)] Module[bsf.dll]bs::ct::openGlErrorCallback() - 0x8791014592027 File[bsglrenderapi.cpp:2769 (181)] Module[bsfGLRenderAPI.dll]0x8790999212414 Module[ig9icd64.dll]0x8790999212967 Module[ig9icd64.dll]0x8790999213544 Module[ig9icd64.dll]0x8791000680051 Module[ig9icd64.dll]0x8791000643712 Module[ig9icd64.dll]0x8791002115722 Module[ig9icd64.dll]bs::ct::GLSLGpuProgram::initialize() - 0x8791013951817 File[bsglslgpuprogram.cpp:247 (21)] Module[bsfGLRenderAPI.dll]bs::ct::GpuProgramManager::create() - 0x8790973965995 File[bsgpuprogrammanager.cpp:135 (0)] Module[bsf.dll]bs::ct::GpuProgram::create() - 0x8790971407366 File[bsgpuprogram.cpp:106 (34)] Module[bsf.dll]bs::TPass<1>::createPipelineState() - 0x8790969424345 File[bspass.cpp:77 (0)] Module[bsf.dll]bs::ct::Pass::compile() - 0x8790969422855 File[bspass.cpp:203 (0)] Module[bsf.dll]bs::ct::RendererMaterial::RendererMaterial() - 0x8790996461006 File[bsrenderermaterial.h:244 (0)] Module[bsfRenderBeast.dll]bs::ct::IrradianceComputeSHMat::IrradianceComputeSHMat() - 0x8790996474278 File[bsrenderbeastiblutility.cpp:100 (54)] Module[bsfRenderBeast.dll]bs::ct::RendererMaterial::get() - 0x8790996513864 File[bsrenderermaterial.h:160 (0)] Module[bsfRenderBeast.dll]bs::ct::IrradianceComputeSHMat::getVariation() - 0x8790996516797 File[bsrenderbeastiblutility.cpp:172 (0)] Module[bsfRenderBeast.dll]bs::ct::RenderBeastIBLUtility::filterCubemapForIrradiance() - 0x8790996509063 File[bsrenderbeastiblutility.cpp:464 (10)] Module[bsfRenderBeast.dll]bs::ct::generateDefaultIndirect() - 0x8790997728928 File[bsrenderertextures.cpp:235 (0)] Module[bsfRenderBeast.dll]bs::ct::RendererTextures::startUp() - 0x8790997732600 File[bsrenderertextures.cpp:246 (12)] Module[bsfRenderBeast.dll]bs::ct::RenderBeast::initializeCore() - 0x8790995409393 File[bsrenderbeast.cpp:89 (0)] Module[bsfRenderBeast.dll]std::_Invoker_pmf_pointer::_Call() - 0x8790995106644 File[type_traits:16707566 (68)] Module[bsfRenderBeast.dll]std::invoke() - 0x8790995184528 File[type_traits:16707566 (96)] Module[bsfRenderBeast.dll]std::_Invoker_ret::_Call() - 0x8790995105392 File[type_traits:15732480 (0)] Module[bsfRenderBeast.dll]std::_Call_binder,std::tuple<> >() - 0x8790995107399 File[functional:1859 (0)] Module[bsfRenderBeast.dll]std::_Binder::operator()<>() - 0x8790995102824 File[functional:1914 (136)] Module[bsfRenderBeast.dll]std::_Invoker_functor::_Call &>() - 0x8790995106078 File[type_traits:16707566 (62)] Module[bsfRenderBeast.dll]std::invoke &>() - 0x8790995184926 File[type_traits:16707566 (62)] Module[bsfRenderBeast.dll]std::_Invoker_ret::_Call &>() - 0x8790995106174 File[type_traits:15732480 (0)] Module[bsfRenderBeast.dll]std::_Func_impl_no_alloc,void>::_Do_call() - 0x8790995305869 File[functional:15732480 (0)] Module[bsfRenderBeast.dll]std::_Func_class::operator()() - 0x8790960262640 File[functional:15732480 (0)] Module[bsf.dll]bs::CommandQueueBase::playbackWithNotify() - 0x8790963017940 File[bscommandqueue.cpp:127 (0)] Module[bsf.dll]bs::CoreThread::runCoreThread() - 0x8790963430633 File[bscorethread.cpp:118 (0)] Module[bsf.dll]std::_Invoker_pmf_pointer::_Call() - 0x8790963321364 File[type_traits:16707566 (68)] Module[bsf.dll]std::invoke() - 0x8790963345312 File[type_traits:16707566 (96)] Module[bsf.dll]std::_Invoker_ret::_Call() - 0x8790963320624 File[type_traits:15732480 (0)] Module[bsf.dll]std::_Call_binder,std::tuple<> >() - 0x8790963321783 File[functional:1859 (0)] Module[bsf.dll]std::_Binder::operator()<>() - 0x8790963318648 File[functional:1914 (136)] Module[bsf.dll]std::_Invoker_functor::_Call &>() - 0x8790963321022 File[type_traits:16707566 (62)] Module[bsf.dll]std::invoke &>() - 0x8790963345566 File[type_traits:16707566 (62)] Module[bsf.dll]std::_Invoker_ret::_Call &>() - 0x8790963321118 File[type_traits:15732480 (0)] Module[bsf.dll]std::_Func_impl_no_alloc,void>::_Do_call() - 0x8790963395677 File[functional:15732480 (0)] Module[bsf.dll]std::_Func_class::operator()() - 0x8790960262640 File[functional:15732480 (0)] Module[bsf.dll]bs::PooledThread::run() - 0x8790960721335 File[bsthreadpool.cpp:116 (0)] Module[bsf.dll]std::_Invoker_pmf_pointer::_Call() - 0x8790960687908 File[type_traits:16707566 (68)] Module[bsf.dll]std::invoke() - 0x8790960699360 File[type_traits:16707566 (96)] Module[bsf.dll]std::_Invoker_ret::_Call() - 0x8790960687792 File[type_traits:15732480 (0)] Module[bsf.dll]std::_Call_binder,std::tuple<> >() - 0x8790960688167 File[functional:1859 (0)] Module[bsf.dll]std::_Binder::operator()<>() - 0x8790960687400 File[functional:1914 (136)] Module[bsf.dll]std::_Invoker_functor::_Call >() - 0x8790960688014 File[type_traits:16707566 (62)] Module[bsf.dll]std::invoke >() - 0x8790960699470 File[type_traits:16707566 (62)] Module[bsf.dll]std::_LaunchPad >,std::default_delete > > > >::_Execute<0>() - 0x8790960691082 File[xthread:239 (0)] Module[bsf.dll]std::_LaunchPad >,std::default_delete > > > >::_Run() - 0x8790960710909 File[xthread:247 (0)] Module[bsf.dll]std::_LaunchPad >,std::default_delete > > > >::_Go() - 0x8790960708182 File[xthread:231 (0)] Module[bsf.dll]std::_Pad::_Call_func() - 0x8790960706029 File[xthread:209 (0)] Module[bsf.dll]0x8791027371960 Module[ucrtbased.dll]0x8791027370993 Module[ucrtbased.dll]0x2005751581 Module[kernel32.dll]0x2008234077 Module[ntdll.dll]
-- | -- | --

**Comment by BearishSun** [comment]
What is your GPU? Also what is the latest version of  the drivers you have installed?

It looks like OpenGL 4.5 isn't supported by your system/GPU.

**Comment by CharlesHo110** [comment]
> What is your GPU? Also what is the latest version of the drivers you have installed?
> 
> It looks like OpenGL 4.5 isn't supported by your system/GPU.

Intel HD Graphics P530. I installed the driver 21.20.16.4860. While I run the Vulkan version,it still crashed.But I can run the Vulkan's  cube sample.
Maybe bsf need a evaluating system to choose the right driver.

**Comment by BearishSun** [comment]
Your GPU seems to have been released with OpenGL 4.4. Although there have since been driver updates that should have updated to 4.5 or 4.6, they might have been skipped for Win 7 and/or your particular processor. You can verify your OpenGL version by using a tool such as http://realtech-vr.com/admin/glview.

Regarding Vulkan, if you post the error message I can provide further assistance. But if OpenGL 4.5 isn't supported it's quite likely Vulkan is going to lack some extensions as well, causing it to crash.

**Comment by CharlesHo110** [comment]
> Your GPU seems to have been released with OpenGL 4.4. Although there have since been driver updates that should have updated to 4.5 or 4.6, they might have been skipped for Win 7 and/or your particular processor. You can verify your OpenGL version by using a tool such as http://realtech-vr.com/admin/glview.
> 
> Regarding Vulkan, if you post the error message I can provide further assistance. But if OpenGL 4.5 isn't supported it's quite likely Vulkan is going to lack some extensions as well, causing it to crash.

Thank you so much.I checked the OpenGL version and Vulkan version.It's not the newest one. But I just think it shouldn't crash for those samples.^_^  Is there any schedule to support the mobile device for bsf in future?

**Comment by BearishSun** [comment]
Mobile is planned but there isn't a date for it yet, and yes it will come with a lower-end renderer that will be able to run on more devices.
