### ISSUE TITLE
SceneObject::getComponent does not work with components without RTTI implementation

### ISSUE THREAD

**Issue by ataulien** [GameFoundry/bsf#302]
I fell for this one a few times now until I figured out what was causing my issues:

If you call `SceneObject::getComponent` with some component which has *not* been blessed with all the RTTI-foo (Like the ones described here: https://www.bsframework.io/docs/custom_components.html), then it will not return the component you asked it for. Rather it seems to be returning any one component which is derived from `bs::Component`, which they all are.

However, this leads to some pretty tricky issues with code like this:
```cpp
    mCharacterAI = SO()->getComponent<CharacterAI>();

    if (mCharacterAI.isDestroyed())
    {
      REGOTH_THROW(...);
    }
```

At that point, `mCharacterAI` is a valid handle, but it's pointing to an object of the wrong type! So the `isDestroyed()` check passes.

Also the program crashes only *maybe* when accessing memory of `CharacterAI`, often it survives one memory access and fails in some other code because the `this`-pointer is for a completely different object, of course.

Unfortunately there isn't a single word of components needing an RTTI implementation for `getComponent` to work properly in the docs. The example code also suggests it is only needed when you want to persist data.

One improvement would be to add a static assert on whether the RTTI of the component given to `getComponent` is the one of `bs::Component`, since it makes no sense to query for that anyways. Also the docs of `getComponent` and the manual about custom components could mention that...

**Comment by BearishSun** [comment]
I've updated the documentation to more clearly reflect that components require RTTI. Also updated `SceneObject::getComponent` so it doesn't return a random component if a component with no RTTI is provided.
