### ISSUE TITLE
RTTI related headers missing in precompiled package

### ISSUE THREAD

**Issue by ataulien** [GameFoundry/bsf#305]
It seems like the header `bsfCore/Private/RTTI/BsGameObjectRTTI.h`, which is being used to serialize components is not part of the precompiled packages offered on the bs:f-website.

The [documentation](https://www.bsframework.io/docs/serializing_objects.html) suggests creating an RTTI-class for a component with the following snipped inside:

```cpp
SPtr<IReflectable> newRTTIObject() override
{
    return GameObjectRTTI::createGameObject<MyComponent>();
}
```

That `GameObjectRTTI::createGameObject` is defined inside the header I mentioned above. Is this just not the right way to do `newRTTIObject` on a custom component or should the header rather be part of the precompiled package?

**Comment by BearishSun** [comment]
That looks like an oversight. The file should not be private. I'll let you know when it is resolved.

**Comment by BearishSun** [comment]
I've refactored this so that `SceneObject::createEmptyComponent<T>` is used instead, which is now part of the public interface. The documentation has been updated accordingly.
