### ISSUE TITLE
Visual Studio 2019

### ISSUE THREAD

**Issue by M4iKZ** [GameFoundry/bsf#322]
when I open solution generated from cmake with visual studio 2019 (even generated for 2017 version) I lost every file and solution into IDE

![Screenshot (30)](https://user-images.githubusercontent.com/8481797/57197971-b2006700-6f6d-11e9-88b2-747d6c3f5a22.png)

thanks

**Comment by BearishSun** [comment]
Closing as per discussion on Discord.
