### ISSUE TITLE
Warning about type-punned pointer in BsBitwise.h

### ISSUE THREAD

**Issue by hhyyrylainen** [GameFoundry/bsf#330]
Compiling with `gcc (GCC) 8.3.1` I get this warning whenever `bsfUtility/Utility/BsBitwise.h` is included. Here's the warnings:
```
/home/hhyyrylainen/Projects/Leviathan/build/ThirdParty/include/bsfUtility/Utility/BsBitwise.h: Staattinen jäsenfunktio ”static float bs::Bitwise::float10ToFloat(bs::UINT32)”:
/home/hhyyrylainen/Projects/Leviathan/build/ThirdParty/include/bsfUtility/Utility/BsBitwise.h:682:12: varoitus: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *(float*)&output;
            ^~~~~~~~~~~~~~~
/home/hhyyrylainen/Projects/Leviathan/build/ThirdParty/include/bsfUtility/Utility/BsBitwise.h: Staattinen jäsenfunktio ”static float bs::Bitwise::float11ToFloat(bs::UINT32)”:
/home/hhyyrylainen/Projects/Leviathan/build/ThirdParty/include/bsfUtility/Utility/BsBitwise.h:722:12: varoitus: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    return *(float*)&output;
            ^~~~~~~~~~~~~~~
```

**Comment by BearishSun** [comment]
Thanks. Ideally we want to get rid of all warnings, but this doesn't seem too high priority considering the types are the same size. Might just end up silencing the warning.

**Comment by hhyyrylainen** [comment]
I just pulled from master and now a ton of files seem to include the BsBitwise.h header:
```
In file included from /home/hhyyrylainen/Projects/Leviathan/build/ThirdParty/include/bsfUtility/Utility/BsBitstream.h:10,
                 from /home/hhyyrylainen/Projects/Leviathan/build/ThirdParty/include/bsfUtility/Reflection/BsRTTIPlain.h:8,
                 from /home/hhyyrylainen/Projects/Leviathan/build/ThirdParty/include/bsfUtility/Reflection/BsRTTIField.h:6,
                 from /home/hhyyrylainen/Projects/Leviathan/build/ThirdParty/include/bsfUtility/Reflection/BsRTTIType.h:10,
                 from /home/hhyyrylainen/Projects/Leviathan/build/ThirdParty/include/bsfCore/Scene/BsSceneObject.h:9,
```

Now when compiling my project I get a ton of warnings from bsf because of that. Could this be made a higher priority to fix?

**Comment by BearishSun** [comment]
I'd be open for a PR, otherwise I'll try to get around to it, but it's hard to justify fixing a warning with so much on my plate atm.

**Comment by hhyyrylainen** [comment]
How should this be fixed? From searching the issue, the right move seems to be to add a std::memcpy call. Then relying on the compiler to basically remove the extra copy with optimization.
Another option is disabling the warning.

**Comment by BearishSun** [comment]
Not sure what's the best way to fix. Disabling the warning works for me.

**Comment by hhyyrylainen** [comment]
I would primarily go for the memcpy solution as that is the correct approach according to C++ standard. I asked first before doing that as I've talked to a project maintainer who wanted to do non standard things (and disable warnings) in order to not have to rely on the optimizer to do the right thing.

**Comment by BearishSun** [comment]
Perhaps `union` would work as well?

**Comment by hhyyrylainen** [comment]
That would probably quiet the warning, but AFAIK reading the non-active member of an union is undefined behaviour.

**Comment by BearishSun** [comment]
Right, memcpy it is then.

**Comment by hhyyrylainen** [comment]
I made a pull request: https://github.com/GameFoundry/bsf/pull/398
