### ISSUE TITLE
Shadow acne from directional lights

### ISSUE THREAD

**Issue by jkunstwald** [GameFoundry/bsf#332]
When adding a directional light to the "Physics" example in bsfExamples like this:

```C++
HSceneObject sunSO = SceneObject::create("Sky");
sunSO->yaw(Degree(-45));
sunSO->pitch(Degree(-45));
HLight sun = sunSO->addComponent<CLight>();
sun->setType(LightType::Directional);
sun->setCastsShadow(true);
```

and walking around the scene, a lot of shadow acne is visible on the floor from certain angles:

![shadow acne](https://user-images.githubusercontent.com/17261478/57878769-0e3f7280-781b-11e9-82d4-a168a0e1aed8.PNG)

![shadow acne 2](https://user-images.githubusercontent.com/17261478/57878786-1a2b3480-781b-11e9-9b34-ecb30ffa57c7.PNG)

**Comment by BearishSun** [comment]
Try tweaking the shadow bias parameter, the default value might not be appropriate.

**Comment by ataulien** [comment]
I think one reason for the shadow acne being so bad is that the ground is a plane. If bsf renders shadows using backfaces, you may get better results when making the ground solid, by using a large cube, for example.

**Comment by BearishSun** [comment]
Yep, you're right, that's likely the bigger issue here. Shadows work best with geometry that has thickness due to backface rendering.

**Comment by jkunstwald** [comment]
Thank you, i didn't think about the plane / front face culling!
