### ISSUE TITLE
OpenGL on Linux broken

### ISSUE THREAD

**Issue by ErrorFlexXx** [GameFoundry/bsf#334]
With the following commit 9515eadf62790ecb57ea5e8ab6332247814d4869 OpenGL stopped working for me on linux (I found the commit to be the issue with git bisect).

It's crashing at BsGLSupport.cpp:22
```cpp
const GLubyte* pcVer = glGetString(GL_VERSION);
```
returning a nullptr.
Seems like the OpenGL context is no longer initialized since the mentioned commit.

**Comment by BearishSun** [comment]
Thanks for the report, and especially for tracking it down to a particular commit. I submitted a fix that should resolve the issue in 5f2869513689ee8999aa5be556d0f55b4adf07c8.

**Comment by ErrorFlexXx** [comment]
Many thanks for the very quick reply.
Just tested it, the issue is resolved.

One quick question before closing the resolved issue :D :
Do you really need `cmake_minimum_required (VERSION 3.11.0)` or would VERSION 3.10.2 be ok, too ?
I only have version 3.10.2 currently and don't have any problems with that.

**Comment by BearishSun** [comment]
I don't know. It might work fine on all platforms, it might not. It would require testing on all supported platforms.

**Comment by ErrorFlexXx** [comment]
Ok, thank you.

The problem will solve itself over time anyway, as new distros are shipping cmake in 3.13.4.
:+1:
