### ISSUE TITLE
Integrate EnTT ECS components

### ISSUE THREAD

**Issue by pgruenbacher** [GameFoundry/bsf#339]
This isn't a feature request so much as me just writing out an issue to track my thoughts on the matter. I'm going to be evaluating bs framework for whether EnTT can be used as an alternative scene framework. Luckily bsf is already composition-friendly from what I can tell. 

@BearishSun I should just make a Source/Plugin/bsfEnTT plugin right when I fork and play around right?

**Comment by BearishSun** [comment]
`Source/Plugin/bsfEnTT` sounds good. Although you don't have to make it an actual separate shared/dynamic library as other plugins. Files can reside in that folder, but can link with the main `bsf` library, perhaps controlled by an optional CMake flag.

**Comment by pgruenbacher** [comment]
agreed.

**Comment by pgruenbacher** [comment]
A big bonus of using EnTT reflection would be that the component and classes would no longer need to inherit from IReflectable for the current RTTI reflection system. However @skyjack I haven't seen an example of serialization / deserialization using EnTT reflection if that's even a thing. I was just gonna use cereal but I'd be curious how well EnTT reflection fits with serialization.

**Comment by skypjack** [comment]
It's primarily meant for that actually.

The possibility of attaching free functions to meta types as if they were fake member functions is intended if you want to create built-in, per type serialization functions without having to extend your types. Otherwise you can literally walk through the meta types with a generic serialization system and serialize a field at a time.  
In fact, it supports different models for serialization. It's a matter of taste to decide what's the preferred one before to proceed.

Note: `meta` requires C++17.

**Comment by pgruenbacher** [comment]
Some more notes going through the code.

1. At >200,000 lines of code this is really well documented and maintained code. I'm using it as an example framework from now on.
2. The biggest pain point from a contributor standpoint is the amount of code necessary to handle the simulation/core thread synchronization between the Object and ct::Objects. It's hard for me to decide whether the ECS module should just disregard MT completely for now. My guess is yes for prototype purposes. Though @skypjack 's new responsive observer features may be useful when it comes to syncing dirty components.

3. Two options: it could come with a separate bsfRenderECS plugin as well, since the main benefits would be the visibility culling, depth ordering,
4. Other option: Many of the ECS benefits come from the simulation side and state updates, so instead the entities could instead just be coupled to the scene objects for rendering, so that all game logic can still happen on the ECS without worrying about rendering. 

It's hard to say... maybe a high entity count scene should be generated for testing purposes as the very first objective to see when bsfRenderBeast starts to strain. @BearishSun have you formed any opinions about how ECS would benefit / not-benefit the framework.

**Comment by BearishSun** [comment]
I think it would be nice to have all the engine internals run on a unified ECS system, which can then also be utilized by users that need high performance without having to dig into individual systems. Ideally it would serve as a high-performance way to extend systems like the renderer, animation, particle system, etc., but also for generic simulation purposes.

Unity has special rules for their ECS regarding threading and how it handles data copying. Perhaps something like that can be employed here. I'm guessing it would work similarly to core object syncing.

But all in all it would be a huge overhaul and we should start "small". I agree the initial focus should be just the renderer, and perhaps even just the core-thread part of the renderer (no MT syncing). 

`bsfRenderECS` sounds good, although many parts of the current renderer are built-into `RenderBeast` and you would likely want to re-use many of those (e.g. various `RenderMaterial`s such as tonemapping, tiled deferred, etc. and even helper classes for shadow mapping and similar). So as you build it, I wouldn't be opposed if you pull parts of `RenderBeast` into the core of bsf, so you can use it for your own plugin (as this was something I was planning to do myself).

**Comment by pgruenbacher** [comment]
yes there's a lot of useful logic in renderBeast. Well in that case I'll probably just get a rought prototype going without worrying about any sort of re-using of existing MT / reflection / serialization logic. This will keep the components much simpler.

**Comment by pgruenbacher** [comment]
I'm basically using my initial fork branch to push everything I want into bsf https://github.com/GameFoundry/bsf/pull/341. 

The plan is to actually update bsfRenderBeast's sceneInfo, visibilityINfo, cullInfo as the starting point, since those vectors translate very well to EnTT api. The getRendererId() of renderables means that theoretically the current scene structure of scene objects will still be compatible with the ECS backend which is great, while still having an ECS registry exposable for a person to take advantage of without having to make thousands of scene objects.

Some other notes: the applicationCore will need to have a runLoopSteps() that will run a certain # of steps before exiting, allowing for more integrated unit-testing.

**Comment by BearishSun** [comment]
Sounds good. We'll probably want to add `Application::runOnce` or something similar, then users can run a loop step on demand. I've also had requests for this for other use cases.  Although there might be challenges how the implementation handles this (I took a quick glance once I don't think the solution was trivial, but I forgot the details).

**Comment by pgruenbacher** [comment]
yea I've got runMainSteps(UINT32 steps) and then moved the actual loop logic into CoreApplication::Update().

**Comment by pgruenbacher** [comment]
![Screenshot from 2019-06-15 13-20-12](https://user-images.githubusercontent.com/3332598/59554420-84e1a400-8f70-11e9-8da5-2e24fd55bfbb.png)

shadows, lights, decals, renderables, and particles all seem to be working with the ECS refactor. Of course this is a incremental refactor so it's not necessarily an improvement in performance yet, but it's getting there...

Basically the easiest thing to refactor was the Renderer module scene info, which had independent vector containers for each light, renderable, decal, particle instance. The EnTT registry api was relatively easy to replace those containers.  This simplifies a lot of code that was originally involved with recycling space in those container when the renderer was registrying/deregisterying instances. It also gets rid of the need of the rendererView and rendererLight instances from having to track their own vector containers for visibility and light data. The other cool thing is that the existing Scene api still plays well with the RenderECS module.

https://github.com/GameFoundry/bsf/pull/341 see my pull branch for reference.

**Comment by pgruenbacher** [comment]
the view visibility was kinda hacked in that instances visible for one view are visible to all views, but that's just cause I introduced a global CVisible component instead of each rendererView tracking its own visible ids. Theoretically CVisible component would have perView flags but I haven't updated it fully yet.

**Comment by BearishSun** [comment]
Awesome work, nice to see it rendering already. I'll check out the code when I get a moment.

**Comment by pgruenbacher** [comment]
I suppose next steps for me are to keep investigating the multi-views functionality, then maybe start looking for the optimizations. Also will be interested in implementing gpu-instancing and LOD but I'll need guidance on that likely. Also need to start thinking on the ECS scene api itself, since the biggest benefit of the ECS renderer is that scene objects and the notifications won't be necessary.

It'd be very useful to have screenshot(<filename>) since it could then be possible to have all the test suites generate a gallery of renderings to validate without having to manually test. I've yet to see an automated render test suite for any engine library which is really really surprising since that would be very useful for platform testing and validating graphics features.

**Comment by BearishSun** [comment]
I thought about image based unit tests but images will likely not look the same on different platforms or hardware, which is hard to handle - some kind of fuzzy comparison perhaps? Also I have a feeling it would be a PITA to keep maintaining the reference images as changes to the renderer are made.

GPU instancing and LOD both sound like great additions.

**Comment by pgruenbacher** [comment]
oh definitely not for automated comparison or regression... for user comparison and dev purposes. like it could just generate documentation-like pages that could then be referenced visually. So if someone wanted to test soft shadows, they'd run the RenderingTestSuite.TestSoftShadows which runs the unit-test and generates a reference image/render of the soft-shadow. 
Ultimately to be able to do major refactors, run full test-suite, then pull up the generated image pages locally on browser to test everything looks right. easier than manually complex scenes because it leads to difficulty isolating issues.

**Comment by pgruenbacher** [comment]
these would also be used for automated image documentation too.

**Comment by BugBiteSquared** [comment]
Any progress on this? I'm looking into using bsf with EnTT as well. Seems it's a non-trivial task to make them play nice with each other.

**Comment by skypjack** [comment]
@BugBiteSquared I'd be interested to know what the difficulties are. It could help me to understand what's missing in the library and what are the features to put in the roadmap to facilitate this type of tasks. Thank you. :wink:

**Comment by pgruenbacher** [comment]
@BugBiteSquared 
I'm working on own engine instead now based on bgfx and entt, but its not public anytime soon.
Main reason is cause I knew what I wanted for game so the generic engines are more trouble than worth. e.g. i have zero need of scene editor
https://github.com/pgruenbacher/bsf/tree/fix_sse/Source/Plugins/bsfECSRenderer this is where I left off on bsf ECS renderer, it may still work though 2 months old.

I'll gitter chat you @skypjack as things progress.
