### ISSUE TITLE
what is the differents between bgfx?

### ISSUE THREAD

**Issue by jaccen** [GameFoundry/bsf#343]
what is the differents between bgfx?
support android ?

**Comment by jayrulez** [comment]
Android is not currently supported.

bgfx is just a rendering engine. bsf is a full fledged game development framework.

bgfx is somewhat equivalent to just the RenderAPI+RenderAPI plugins part of bsf.

**Comment by BearishSun** [comment]
Please post further questions on discord or discourse, github is reserved for bugs and feature requests.
