### ISSUE TITLE
Discord link not working

### ISSUE THREAD

**Issue by woubuc** [GameFoundry/bsf#344]
I'm trying to join the Discord as linked from the repo's readme, but I get an error message saying "this invite may be invalid, or you may not have permission to join".

Also, the name of the Discord server the invite links to is "Banshee 3D" and not "BS::Framework".

**Comment by BearishSun** [comment]
The Discord lists the invite link as valid. Any chance you have perhaps reached the 100 server limit on your account?

Banshee 3D is the shared discord we use for both projects.

**Comment by woubuc** [comment]
It seems to be a Discord issue. I've logged in on the Discord website and I was able to join, but when I wasn't logged in clicking "join" resulted in an error rather than showing the login screen.

In any case, the link is indeed valid.
