### ISSUE TITLE
Suggestions on Threads

### ISSUE THREAD

**Issue by clojur** [GameFoundry/bsf#347]
能否实现一个像Unity3D那样的jobsystem？
如果像Unity3D那样的线程有难度，你也可以参考dwThreadPool这个开源库(https://github.com/diharaw/dwThreadPool)，它实现了无锁高效线程管理。
Can we implement a job system like Unity3D?
If threads like Unity3D are difficult, you can also refer to dwThreadPool(https://github.com/diharaw/dwThreadPool), an open source library that implements lock-free and efficient thread management.

**Comment by BearishSun** [comment]
What is the problem with existing `TaskScheduler` class?

**Comment by clojur** [comment]
It's not lock-free programming. It's not as efficient as atomic, is it?

**Comment by BearishSun** [comment]
The library you linked is not lock-free either. 

And regarding the efficiency that depends on a particular use case and requires profiling, Lock-free is often a trade-off as it requires a lot of additional data copying, and considering mutexes are atomics  under the hood, it you keep the locked for short periods the performance difference can be minimal.

**Comment by clojur** [comment]
thank for your answer
