### ISSUE TITLE
imgui plugin [feature]

### ISSUE THREAD

**Issue by pgruenbacher** [GameFoundry/bsf#351]
I've started another branch for imgui plugin while I wait for feedback on the ECS renderer. 
https://github.com/pgruenbacher/bsf/blob/imgui/Source/Plugins/bsfImgui/Src/imgui_impl_bsf.cpp

This issue is just to track these feature changes. It seems pretty straight forward enough in terms of mapping BsInput to the imgui io. We'll see if it the existing imgui vulkan and opengl implementations can be used directly.

**Comment by jayrulez** [comment]
Could is not be done through a render extension and the bsf render api instead of using the native render apis directly?

**Comment by pgruenbacher** [comment]
not sure yet. I think the way other people do it is they pick native render apis first, and then migrate it to the render api. first baby step is just getting something working first locally.
that being said the render implementation is pretty simple when you look at existing samples so I'm not worried about it.

**Comment by pgruenbacher** [comment]
and ultimately I see the benefit of imgui support is that it can hopefully reduce the code complexity of tool interfaces, while not being used in the actual game ui itself. I find the complex imgui demos to be pretty succint compared to stateful gui components.

**Comment by pgruenbacher** [comment]
@jayrulez I also see what you mean by the render extension too now, it looks like it could behave similar to how GUI manager has its own GUI render extension. 

Looking through the GUI code, I definitely don't think imgui should serve as a replacement for the GUI code which is much more flexible it seems in terms of rendering 3d gui especially. It may still be useful to have maybe a builtin scene editor using imgui as a milestone goal. If anything this will still be learning exercise.

**Comment by pgruenbacher** [comment]
I'm in a bit of decision paralysis. how would replicate this opengl implemenation in bsf?

```
        const ImDrawList* cmd_list = draw_data->CmdLists[n];
        const ImDrawVert* vtx_buffer = cmd_list->VtxBuffer.Data;
        const ImDrawIdx* idx_buffer = cmd_list->IdxBuffer.Data;
        glVertexPointer(2, GL_FLOAT, sizeof(ImDrawVert), (const GLvoid*)((const char*)vtx_buffer + IM_OFFSETOF(ImDrawVert, pos)));
        glTexCoordPointer(2, GL_FLOAT, sizeof(ImDrawVert), (const GLvoid*)((const char*)vtx_buffer + IM_OFFSETOF(ImDrawVert, uv)));
        glColorPointer(4, GL_UNSIGNED_BYTE, sizeof(ImDrawVert), (const GLvoid*)((const char*)vtx_buffer + IM_OFFSETOF(ImDrawVert, col)));
```
from https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_opengl2.cpp
I thought maybe VertexBuffer, but it doesn't seem likely. I also thought maybe doing BsMeshHeap but it seemed wasteful to copy data from imgui to the meshHeap. also I couldn't figure out how to do `setVertexData` with a stride option.

**Comment by pgruenbacher** [comment]
I much prefer how bgfx accomplishes this. 
```
			ImDrawVert* verts = (ImDrawVert*)tvb.data;
			bx::memCopy(verts, drawList->VtxBuffer.begin(), numVertices * sizeof(ImDrawVert) );
```

what would the equivalent of that be in bsf?

**Comment by pgruenbacher** [comment]
ok i might have figured that part out https://github.com/pgruenbacher/bsf/blob/3d467975dabf05ce57db3ed54dcf610f007ca5e9/Source/Plugins/bsfImgui/Src/bsfImguiRenderAPI.cpp#L121

now I just need to setup the GpuParams I think.

**Comment by pgruenbacher** [comment]
@BearishSun compared to the low-level rendering example, I though I'd try making a material and applying it to the renderAPI using the gRendererUtility before doing the drawIndexed, but I don't think I'm doing it right... is it obvious to you a better way of rendering? https://github.com/pgruenbacher/bsf/blob/imgui/Source/Plugins/bsfImgui/Src/bsfImguiRenderAPI.cpp

This is usually the part where I give up because graphics programming is not my forte

**Comment by BearishSun** [comment]
Yeah that looks like the gist of it. I'd use `RenderDoc` to debug a frame and see exactly how rendering happens, and where things go wrong.

**Comment by pgruenbacher** [comment]
ok well good to know. I'll probably make a RendererExtension and follow how the GuiManager does its rendering maybe to debug. I hate graphics debugging.

**Comment by pgruenbacher** [comment]
@BearishSun plugin appears to be all working. I can clean it up, integrate some extra 3rd-party gizmos, and make a PR to be a standard plugin? If PR will be accepted I'll write to the documentation as well.

**Comment by jayrulez** [comment]
Hello @pgruenbacher . Nice work you have done. I mentioned before but I'll do so here again. The imgui plugin can be contained in a render extension instead of a standard bsf plugin.

This way imgui does not need to be a part of the source tree for those that are not interested in it.
Also, imgui and plugin would be built as a part of your application instead of part of the framework.

If you are interested in doing it like this I could be of help.

May @BearishSun can create an official *extensions* repo for housing things like this.

Regards.

**Comment by pgruenbacher** [comment]
I guess separate repo can be fine too. I think I'd prefer it to be part of the https://github.com/GameFoundry project space then? Ideally it should be part of the continuous testing. Also would be ideal if there were a standard way of pulling the plugin into the framework if so desired.

**Comment by pgruenbacher** [comment]
and yea, I can have the whole thing be wrapped up as a ImguiRendererExtension class that can be created and destroyed. And then maybe the user can just register imgui function objects that will be called every frame by the rendererExtnesion object manager.

**Comment by pgruenbacher** [comment]
got it working multi-threaded. phew. Wish I had tried the cloning the cmd lists first.
Should be relatively cleaned up if you want to look it over @BearishSun 
It's tacked on top of my ECS rendering fork (cause it had the unit-tests as well). I was going to wait to refactor it into proper PR (or new repo) depending on what you think best approach will be. 
![demoImgui](https://user-images.githubusercontent.com/3332598/60750668-1e9ddf00-9f7a-11e9-9664-2a4b9b68b186.gif)

**Comment by BearishSun** [comment]
Nice work. Can you please make the split into a separate branch/repo. It makes it much harder to review with a lot of extra changes.

Also we're going to go with a separate repository approach, but linked as a submodule, as discussed on discord.

If you want the repository to be part of `GameFoundry` organization also make sure to closely follow the code style, as well as fully document the code. I'd prefer these to be done before I do a detailed review to avoid having to do it multiple times.

**Comment by pgruenbacher** [comment]
ok i'll make a separate repo.

**Comment by pgruenbacher** [comment]
PR is made I consider this done.
