### ISSUE TITLE
openGL renderAPI scissor not immediate

### ISSUE THREAD

**Issue by pgruenbacher** [GameFoundry/bsf#356]
compare the GL render api https://github.com/GameFoundry/bsf/blob/46f13bf0d3cb112296f1305d1eb5b54c8f3a4d5f/Source/Plugins/bsfGLRenderAPI/BsGLRenderAPI.cpp#L1281-L1292

to the D3D11 render api implementation.
https://github.com/GameFoundry/bsf/blob/46f13bf0d3cb112296f1305d1eb5b54c8f3a4d5f/Source/Plugins/bsfD3D11RenderAPI/BsD3D11RenderAPI.cpp#L870-L883

I noticed this when doing the imgui implementation. https://github.com/pgruenbacher/bsf/blob/020e89a68feb84defeaaa59386d6036bafa4e74c/Source/Plugins/bsfImgui/Src/BsImguiRenderer.cpp#L238
it appears that the glScissor is only called when enableScissor is called. One way was to re-update the graphicsPipeline. Other way was I just updated the render api to do glScissorRect. However now there's the issue that the glScissorRect is being called redundantly.
https://github.com/pgruenbacher/bsf/blob/020e89a68feb84defeaaa59386d6036bafa4e74c/Source/Plugins/bsfGLRenderAPI/BsGLRenderAPI.cpp#L1281

**Comment by pgruenbacher** [comment]
my guess is that the setScissorTestEnable in the gl render api needs to be updated as well, maybe get rid of the following lines? https://github.com/GameFoundry/bsf/blob/46f13bf0d3cb112296f1305d1eb5b54c8f3a4d5f/Source/Plugins/bsfGLRenderAPI/BsGLRenderAPI.cpp#L1758-L1766

**Comment by BearishSun** [comment]
This should be resolved on latest.

**Comment by pgruenbacher** [comment]
confirmed to work.
