### ISSUE TITLE
Access violation in Win32Input::CheckXInputDevices cleanup

### ISSUE THREAD

**Issue by danchia** [GameFoundry/bsf#358]
I get an access violation at [1] during cleanup, presumably because we always unconditionally release devices even if the array is not guaranteed to be initialized.

Note: this only happens when I have a gamepad connected.

[1] https://github.com/GameFoundry/bsf/blob/master/Source/Foundation/bsfCore/Private/Win32/BsWin32Input.cpp#L139

**Comment by BearishSun** [comment]
Thanks for tracking it down, I submitted a fix. I was unable to reproduce the issue, even with gamepad connected, so I cannot confirm a fix, but that should be it. If the problem still occurs please reopen the issue.
