### ISSUE TITLE
Clarify threading model for Component update and events

### ISSUE THREAD

**Issue by danchia** [GameFoundry/bsf#360]
Component updates and event callbacks could use more clarity around the threading model. My current understanding is that everything happens serially. In particular:

* Component updates never overlap - i.e. we don't have to worry about two components being concurrently updated. This is important, as during Component A update we may want to invoke some code in Component B (e.g to deal damage to B). If B was being updated concurrently we would need to worry about concurrency issues.

* A similar argument could be made for event callbacks - two registered event callbacks should not happen at the same time.

**Comment by pgruenbacher** [comment]
the main simulation thread has no concurrency that I know of. save with event callbacks. there is multi-threading in the core thread for specific private implementations (physics, rendering, etc.) but that shouldn't affect the main thread ever.

**Comment by BearishSun** [comment]
Indeed, there is no concurrency for either of those.
