### ISSUE TITLE
Xsc::Reflection::UniformType not exist.

### ISSUE THREAD

**Issue by hungry0** [GameFoundry/bsf#371]
<img width="858" alt="QQ20190714-094338@2x" src="https://user-images.githubusercontent.com/13111009/61178255-0e41d000-a61c-11e9-8b80-43a962b253b9.png">

**Comment by hungry0** [comment]
v1.1.0 or v1.0.0 or master

**Comment by BearishSun** [comment]
Locally, as well as CI, macOS version appears to be compiling fine. Make sure to run cmake in order so it grabs the latest dependencies package. If that doesn't work try a fresh checkout.

**Comment by hungry0** [comment]
actually, I am in China, the CMake download file never works fine, so I download the dependencies manually.

**Comment by TumblerSGQ** [comment]
an solution? The same problem too

**Comment by BearishSun** [comment]
If it works manually, download the latest dependencies packages and overwrite the existing ones.

**Comment by TumblerSGQ** [comment]
> If it works manually, download the latest dependencies packages and overwrite the existing ones.

I looked at the code . It should be : case Xsc::Reflection::VariableType::Variable,not UnitformType ?

**Comment by BearishSun** [comment]
It depends on which version of bsf you have, the API changes and you need to make sure you have matching dependencies. You can't mix and match different source code and dependency versions.

**Comment by TumblerSGQ** [comment]
![image](https://user-images.githubusercontent.com/12553991/61185173-9c53a000-a688-11e9-887e-569adae42ff9.png)

I use the master bsf.
What does this mean? the Assert will always false

**Comment by BearishSun** [comment]
That's not the latest master version. Master is `VERSION = 2`. You are likely using data files from a newer version with older source code.

**Comment by hungry0** [comment]
I really hope that you can provide a full version and a full version of the case because the download of CMake is too easy to go wrong, so far I have tried dozens of times, but will be stuck in a certain step.
