### ISSUE TITLE
Direct3D11 texture writeData crash when discardEntireBuffer is false

### ISSUE THREAD

**Issue by hhyyrylainen** [GameFoundry/bsf#378]
I think I found a bug in Direct3d11 render backend. When I change the “discardEntireBuffer” parameter in `Texture::writeData` call ( `Texture->writeData(DataBuffer, 0, 0, false);` ) to false I get a crash. When it is true everything seems to work.

Non-crashing code is: `Texture->writeData(DataBuffer, 0, 0, true);`

Screenshots of visual studio are in this thread:
https://discourse.bsframework.io/t/crash-with-direct3d11-when-discardentirebuffer-is-false/484

**Comment by BearishSun** [comment]
Thanks for the report. Do you have code that creates the texture and the data buffer? I cannot reproduce with a trivial test.

**Comment by hhyyrylainen** [comment]
The full code is here: https://github.com/hhyyrylainen/Leviathan/blob/15e0e4a76576f03b5e631cdb4be713dee009c358/Engine/GUI/GuiView.cpp#L432

Changing line 495 to
```
Texture->writeData(DataBuffer, 0, 0, false);
```
will make the crash always happen.

**Comment by BearishSun** [comment]
Thanks. Should be 'fixed' on latest. It's not really a fix - DirectX simply doesn't support normal writes on dynamic textures, they need to be either discard or no-overwrite. The system will now fallback to discard and log a warning instead of crashing.
