### ISSUE TITLE
Downloading the dependencies fails with bad internet

### ISSUE THREAD

**Issue by crodnu** [GameFoundry/bsf#379]
Hi

I'm trying to build bsf, but the download of the dependencies (https://data.banshee3d.com/bsfDependencies_VS2015_Master_11.zip) fails very consistently, i think due to my poor internet connection (i live in Uruguay).

**Comment by BearishSun** [comment]
Thanks for the report. I'm aware of the issue and we're tracking it here: https://github.com/GameFoundry/bsf/issues/291. I don't have an ETA when we might have a proper fix - for now the solution is to download the data files manually and extract the .zip.

I'll close this issue but feel free to comment in the one I linked.
