### ISSUE TITLE
Hi，Ask a question about the allocator.

### ISSUE THREAD

**Issue by hungry0** [GameFoundry/bsf#392]
Hi, When I browsed the code about allocator, I found that the allocator used by FrameVector is StdAlloc<char, FrameAlloc>, but the allocate function of StdAlloc calls bs_alloc<Alloc>, and finally calls this,
`static void* allocate(size_t bytes)
		{
#if BS_PROFILING_ENABLED
                         incAllocCount();
#endif

			return malloc(bytes);
		}`
This seems to have nothing to do with FrameAlloc, Is there a problem with my understanding? thank you for your work.

**Comment by BearishSun** [comment]
A specialization of `MemoryAllocator<T>::allocate()` is called, `MemoryAllocator<FrameAlloc>::allocate()` which internally calls `bs_frame_alloc` and not `malloc`.
