### ISSUE TITLE
bsfUtility/Utility/bsServiceLocator should probably use std::atomic<> for the pointer storage

### ISSUE THREAD

**Issue by jonesmz** [GameFoundry/bsf#46]
There's no comments in the bsfServiceLocator.h file indicating that this utility class can or can't be used in a multi-threaded way.

By wrapping the storage for ServiceLocator::mService in std::atomic<>, the class gains multi-threaded safety very cheaply.

**Comment by BearishSun** [comment]
Yep, makes sense.
