### ISSUE TITLE
Use <cstdint>in bsfUtility/BsTypes.h

### ISSUE THREAD

**Issue by jonesmz** [GameFoundry/bsf#48]
Currently BsTypes.h's typedefs are defined as such.

    namespace bs
    {
        typedef char INT8;
        typedef unsigned char UINT8;
        typedef short INT16;
        typedef unsigned short UINT16;
        typedef int INT32;
        typedef unsigned int UINT32;

    #if BS_COMPILER == BS_COMPILER_MSVC
        typedef unsigned __int64 UINT64;
        typedef __int64 INT64;
    #else
        typedef unsigned long long UINT64;
        typedef long long INT64;
    #endif
    }

We can replace these with the types in <cstdint>

    namespace bs
    {
        typedef std::int8_t INT8;
        typedef std::uint8_t UINT8;
        typedef std::int16_t INT16;
        typedef std::uint16_t UINT16;
        typedef std::int32_t INT32;
        typedef std::uint32_t UINT32;
        typedef std::int64_t UINT64;
        typedef std::uint64_t INT64;
    }

**Comment by jonesmz** [comment]
I'd argue that it'd be easier for new contributors to just use std::[u]int*_t than the bs::[U]INT* types, for nothing else than simple familiarity with the standard types.

Are you opposed to replacing bs::[U]INT* with the std types?

We could do

    namespace bs
    {
        using std::int8_t;
        using std::uint8_t;
        using std::int16_t;
        using std::uint16_t;
        using std::int32_t;
        using std::uint32_t;
        using std::int64_t;
        using std::uint64_t;
    }

To avoid always having to append std to the int names..

**Comment by BearishSun** [comment]
I'm torn regarding the std types. It's something I'd like to switch to, but I also don't want to refactor the entire codebase replacing all the usages of existing types in fear it will break code layout if done in an automated way. At the same time I don't feel like using two different naming schemes.

But I guess the change has to start somewhere, so ultimately I wouldn't be opposed towards using the std types for all new code, and convert older code slowly towards it as well.
