### ISSUE TITLE
JSON format for GUISkin

### ISSUE THREAD

**Issue by BearishSun** [GameFoundry/bsf#56]
GUISkin can currently only be defined from code. This results in some very large blocks of code for the built-in skin in `BuiltinResources`, and also prevents easy modification. It would be better to establish a JSON format for GUISkin and then import all the properties from there.

**Comment by jonesmz** [comment]
You might consider, as an example, the ui XML format from the Qt project for the C++ widgets. Not saying to adopt that, just that it's an example to learn from, so you might be able to avoid some pitfalls.

**Comment by BearishSun** [comment]
Thanks, sounds like a good reference. I probably won't be adopting a full data driven GUI approach just yet, currently just the GUI skin is an issue, but it's certainly something to consider for the future.
