### ISSUE TITLE
Consider enabling -Wextra

### ISSUE THREAD

**Issue by jonesmz** [GameFoundry/bsf#68]
I enable -Wextra in all of my projects. While the warnings that it generates aren't quite as dangerous to ignore as -Wall, resolving those warnings tends to result in a codebase that's quite a bit more robust to hard to solve problems.

**Comment by BearishSun** [comment]
It probably wouldn't hurt.

I do believe I've tried it at some point, but felt it resulted in adding extra lines to just fix the warning messages, in code that isn't really wrong in any way (e.g. unused parameters which are actually used in an #if), without many, or any actual problems reported. If there are other similar situations and a lot of such extra code needs to be added, or significant amount of code needs to be made larger/less clearer just to silence the compiler, I'd avoid it. But I haven't explored the reported warnings enough to know how much of a problem that would be.
