### ISSUE TITLE
Separate include files from source

### ISSUE THREAD

**Issue by jonesmz** [GameFoundry/bsf#77]
This is kind of a big change that I'm proposing, but I think it'll be worth it, so hear me out for a moment.

At the moment, bsf has include files mixed with source files, which in my opinion makes it a little challenging to determine what code is API, and what code is implementation.

A successful project structure that I've used a lot in the past, and use right now at my day job is as follows

 * project/includes/project/grouping/library/*.h
 * project/source/grouping/library/*.cpp

Applying that to bsf would look something like this:

 * bsf/include/bsf/foundation/utility/utility/*.h
 * bsf/include/bsf/foundation/utility/math/*.h
 * bsf/include/bsf/foundation/utility/string/*.h
 * bsf/source/foundation/utility/utility/*.cpp
 * bsf/source/foundation/utility/math/*.cpp
 * bsf/source/foundation/utility/string/*.cpp

In each cpp file, the include for the various header files is very structured. To include BsUUID.h for example, is always

```
#include <bsf/foundation/utility/utility/BsUUID.h>
```

no matter where in the codebase you're including the file from. Further, the entire "include" folder can be installed to the operating system's "/usr/include" directory as a single recursive copy operation, no need to individually select files to copy. Once installed, the same #include statement continues working identically, because the file is still included with the same file structure.

I think that having a hard separation between implementation and declaration provides a lot of benefits to people trying to understand the engine and how to make use of it. For example, at my day job, we use this separation, and are able to reference other code repositories only by "project/group/library/file.h" reliably whether the code being referenced is installed on the system or in another repository in the users home folder, just by adding an include dir to the project.

Consider also that this allows for internal only header files to stay with the source code, instead of being intermixed with the header files that are intended as API types.

We also use our header files as our documentation as well. I mean, technically we have doxygen generated regularly, but almost everyone just reads the header files directly ¯\_(ツ)_/¯.

If you're interested in this change, I'd be happy to do the leg work for it.

**Comment by BearishSun** [comment]
I think the main concern here is that implementation isn't separated from the API. But implementation header files are located in a `Private` sub-folder, which can be skipped when installing. I admit you can't just copy the folder over when installing, but a simple copy with regex does the trick.

Additionally, I've recently done a big refactor to make it this way. There used to be include/source separation (somewhat differently than you're describing though) but I preferred not having two separate hierarchies to maintain. So I'm kinda resistant to doing it again.

If you think your approach has other advantages let me know and we can discuss further.

**Comment by BearishSun** [comment]
I'm gonna close this since I'm happier with the current approach rather than having a separate include tree.
