### ISSUE TITLE
Edit line

### ISSUE THREAD

**Issue by jayrulez** [GameFoundry/bsf#88]
https://github.com/GameFoundry/bsf/blob/9279919f2f58a7bddf2b4124f5ab1d7fb60e89bc/Source/Foundation/bsfEngine/BsApplication.cpp#L116

I'm not able to do a pull request now but I think the line here should be 
loadPlugin("bsfMono", &mMonoPlugin);

**Comment by BearishSun** [comment]
Indeed, you're right, thanks. Fixed with a324b1b6b5b6901c1ad67a2b7bb5e498a136196d.
