### ISSUE TITLE
SBansheeEngine and MBansheeEngine location

### ISSUE THREAD

**Issue by jayrulez** [GameFoundry/bsf#89]
Should these components be a part of this repo instead of the editor repo or is it expected to only use these components while using the editor?

**Comment by jayrulez** [comment]
Okay. Looking forward to that.

Do you plan to do it before or after the 1.0 release?

On a sidenote: As I've gotten a little more time, I've been digging through the internals of the framework and I must say that I am impressed with the quality and clarity of the codebase.
It will be a pleasure to work with in the future.

**Comment by BearishSun** [comment]
Thanks, appreciated.

It will be done after 1.0 release, but I'm not sure when. Most likely very soon after the release, as it hopefully shouldn't be too much work.

**Comment by BearishSun** [comment]
I'm closing this issue as this is technically a part of #17 .
