### ISSUE TITLE
BsAny new/free issue

### ISSUE THREAD

**Issue by nemerle** [GameFoundry/bsf#99]
The `Any::DataBase::clone()` is allocating memory with `new Data`, but `~Any` is using `bs_delete` to free that memory. Shouldn't the `Any::DataBase::clone()` use `bs_new` same as `Any(const ValueType& value) ` constructor ?

**Comment by BearishSun** [comment]
Indeed, it should be using `bs_new`. In fact if you find a new/delete operator anywhere in the framework, it's quite likely in error. I submitted a fix.
